export const NOMS_D_ASSETS_PREMIUM = [
  "veille-basse-cohorte.webp",
  "veille-basse-porte.webp",
  "veille-basse-archives.webp",
  "veille-basse-maelys.webp",
  "haut-puits-vanniers.webp",
  "haut-puits-decanteur.webp",
  "haut-puits-ilyana.webp",
  "nacelles-deux-rives.webp",
  "nacelles-frein.webp",
  "nacelles-trace.webp",
  "nacelles-compagnes.webp",
  "deversoir-ligne-zero.webp",
  "deversoir-conseil.webp",
  "deversoir-chassis.webp",
  "deversoir-passage.webp",
  "trame-barriere-permis.webp",
  "trame-barriere-taxe.webp",
  "trame-piece-regulation.webp",
  "trame-eau-machines.webp",
  "trame-attelage-federe.webp",
  "trame-pompe-renseignement.webp",
  "trame-pompe-filtres.webp",
  "trame-traverse-reservoir.webp",
  "trame-traverse-galerie.webp",
  "trame-traverse-maelys.webp",
  "trame-marche-officiel.webp",
  "trame-marche-clandestin.webp",
  "trame-signal-interface.webp",
  "trame-signal-echo.webp",
  "trame-signal-ilyana.webp",
  "trame-aiguillage-revelation.webp",
  "trame-aiguillage-conseil.webp",
  "trame-aiguillage-passage.webp",
  "couronne-tete-de-ligne.webp",
  "couronne-veille-des-trois.webp",
  "couronne-trois-socles.webp",
  "couronne-montages.webp",
  "couronne-ilyana-plans.webp",
  "couronne-serres-ralliement.webp",
  "couronne-seuil-marche.webp",
  "couronne-seuil-releves.webp",
  "couronne-rampe-couteuse.webp",
  "couronne-maelys-registre.webp",
] as const;

export const LIEUX_PREMIUM = [
  {
    id: "les-vanniers",
    nom: { fr: "Les Vanniers", en: "The Basketmakers" },
  },
  {
    id: "hospice-du-sillon",
    nom: { fr: "Hospice du Sillon", en: "Sillon Hospice" },
  },
  {
    id: "relais-des-vannes",
    nom: { fr: "Relais des Vannes", en: "Sluice Relay" },
  },
  {
    id: "deversoir-noir",
    nom: { fr: "Déversoir Noir", en: "Black Spillway" },
  },
  {
    id: "lisiere-trame-de-fer",
    nom: { fr: "Lisière de la Trame de Fer", en: "Iron Weave Verge" },
  },
  {
    id: "barriere-neuve",
    nom: { fr: "Barrière-Neuve", en: "New Barrier" },
  },
  {
    id: "grand-aiguillage",
    nom: { fr: "Grand-Aiguillage", en: "Grand Junction" },
  },
  {
    id: "pompe-neuve",
    nom: { fr: "Pompe-Neuve", en: "New Pump" },
  },
  {
    id: "traverse-libre",
    nom: { fr: "Traverse-Libre", en: "Free Crossing" },
  },
  {
    id: "marche-des-traverses",
    nom: { fr: "Marché des Traverses", en: "Sleeper Market" },
  },
  {
    id: "signal-zero",
    nom: { fr: "Signal-Zéro", en: "Zero Signal" },
  },
  {
    id: "aiguillage-zero",
    nom: { fr: "Aiguillage Zéro", en: "Zero Junction" },
  },
  {
    id: "couronne-muette",
    nom: { fr: "Couronne muette", en: "Silent Crown" },
  },
  {
    id: "tete-de-ligne",
    nom: { fr: "Tête-de-Ligne", en: "Railhead" },
  },
  {
    id: "veille-des-trois",
    nom: { fr: "Veille-des-Trois", en: "Threefold Watch" },
  },
  {
    id: "serres-de-verre",
    nom: { fr: "Serres-de-Verre", en: "Glasshouses" },
  },
  {
    id: "seuil",
    nom: { fr: "Le Seuil", en: "Threshold" },
  },
] as const;

const RENSEIGNEMENT_D_APPROCHE_DU_DEVERSOIR = {
  id: "approche-du-deversoir",
  source: "nacelliers-des-vannes",
  releveA: 0,
  fiabilite: "rapporte",
  etatAnnonce: "praticable",
  meteo: "rafales-de-cendre",
  panache: "incertain",
  danger: "orniere",
  controlePolitique: "sans-controle-etabli",
  libelles: {
    fr: {
      source: "Dernier relevé transmis par les Nacelliers",
      danger: "Dalles fendues sous une cendre mobile",
      controlePolitique: "Déversoir sans contrôle établi",
    },
    en: {
      source: "Latest survey relayed by the Cable Crews",
      danger: "Cracked slabs beneath moving ash",
      controlePolitique: "Spillway under no established control",
    },
  },
} as const;

const RENSEIGNEMENT_DE_LA_LIGNE_ZERO = {
  id: "ligne-zero-passage",
  source: "techniciens-du-deversoir",
  releveA: 0,
  fiabilite: "confirme",
  etatAnnonce: "praticable",
  meteo: "cendre-basse",
  panache: "absent",
  danger: "conduit-effondrable",
  controlePolitique: "conseil-des-vannes",
  libelles: {
    fr: {
      source: "Interface relevée par les techniciens du Déversoir",
      danger: "Conduit ancien dont la fermeture condamnera l’arrière",
      controlePolitique: "Passage placé sous la décision du Conseil des Vannes",
    },
    en: {
      source: "Interface surveyed by the Spillway technicians",
      danger: "Ancient conduit whose closure will condemn the rear",
      controlePolitique: "Passage governed by the Sluice Council’s decision",
    },
  },
} as const;

const RENSEIGNEMENTS_NACELLES = [
  {
    id: "nacelles-accord-des-bassins",
    source: "nacelliers-des-vannes",
    releveA: 0,
    fiabilite: "confirme",
    etatAnnonce: "praticable",
    meteo: "cendre-basse",
    panache: "absent",
    danger: "cables-fatigues",
    controlePolitique: "accord-des-bassins",
    libelles: {
      fr: {
        source: "Nacelliers mandatés par les deux branches",
        danger: "Câbles fatigués mais contrepoids coordonnés",
        controlePolitique: "Accord des Puits Libres et des Pèlerins",
      },
      en: {
        source: "Cable crews appointed by both branches",
        danger: "Worn cables with coordinated counterweights",
        controlePolitique: "Free Wells and Ash Pilgrims agreement",
      },
    },
  },
  {
    id: "nacelles-passage-conteste",
    source: "nacelliers-des-vannes",
    releveA: 0,
    fiabilite: "rapporte",
    etatAnnonce: "degrade",
    meteo: "rafales-de-cendre",
    panache: "derive-vers-est",
    danger: "cables-fatigues",
    controlePolitique: "passage-conteste",
    libelles: {
      fr: {
        source: "Nacelliers isolés du Relais",
        danger: "Câbles fatigués sous charge non répartie",
        controlePolitique: "Passage contesté par les deux Factions",
      },
      en: {
        source: "Isolated cable crews at the Relay",
        danger: "Worn cables under an unbalanced load",
        controlePolitique: "Crossing disputed by both Factions",
      },
    },
  },
  {
    id: "nacelles-releve-de-branche",
    source: "nacelliers-des-vannes",
    releveA: 0,
    fiabilite: "rapporte",
    etatAnnonce: "praticable",
    meteo: "rafales-de-cendre",
    panache: "incertain",
    danger: "cables-fatigues",
    controlePolitique: "sans-controle-etabli",
    libelles: {
      fr: {
        source: "Relevé transmis par la branche d’approche",
        danger: "Câbles fatigués et contrepoids incomplets",
        controlePolitique: "Mandat des Nacelliers non reconnu",
      },
      en: {
        source: "Survey relayed by the approach branch",
        danger: "Worn cables and incomplete counterweights",
        controlePolitique: "Cable crews’ mandate unrecognized",
      },
    },
  },
] as const;

const LIBELLES_D_OPTIONS_DES_NACELLES = {
  fr: {
    "treuil-principal": "Appui appliqué : treuil principal sous charge contrôlée",
    "contrepoids-de-la-cohorte":
      "Appui appliqué par la Cohorte : contrepoids de charpente étanche",
    "relais-de-l-hospice":
      "Appui appliqué par l’Hospice : relais filtré de la branche basse",
    "accord-des-factions":
      "Appui appliqué par les Factions : cage commune prioritaire",
  },
  en: {
    "treuil-principal": "Applied support: main winch under controlled load",
    "contrepoids-de-la-cohorte":
      "Applied Cohort support: sealed-frame counterweight",
    "relais-de-l-hospice":
      "Applied Hospice support: filtered relay from the lower branch",
    "accord-des-factions":
      "Applied Faction support: priority shared cage",
  },
} as const;

export const TRONCONS_PREMIUM = [
  {
    id: "chemin-des-vanniers",
    extremites: ["haut-puits", "les-vanniers"],
    dureeSecondes: 420,
    etatInitial: "praticable",
    consommationConnue: {
      stock: "combustible",
      quantite: 3,
      unite: "litres",
    },
    consommationIncertaine: {
      stock: "eau",
      minimum: 4,
      maximum: 6,
      quantiteReelle: 5,
      unite: "litres",
      renseignementId: "vanniers-haut-puits-0",
    },
    consequenceDuHalo: {
      fr: "Le panache du Phare dérive vers l’est et atteint les Vanniers.",
      en: "The Lighthouse plume drifts east and reaches the Basketmakers.",
    },
    renseignements: [
      {
        id: "vanniers-haut-puits-0",
        tronconId: "chemin-des-vanniers",
        source: "eclaireurs-de-haut-puits",
        releveA: 0,
        fiabilite: "rapporte",
        etatAnnonce: "praticable",
        meteo: "cendre-basse",
        panache: "incertain",
        danger: "orniere",
        controlePolitique: "sans-controle-etabli",
        libelles: {
          fr: {
            source: "Éclaireurs de Haut-Puits",
            danger: "Ornières profondes",
            controlePolitique: "Sans contrôle établi",
          },
          en: {
            source: "High Well Scouts",
            danger: "Deep ruts",
            controlePolitique: "No established control",
          },
        },
      },
    ],
  },
  {
    id: "chenal-des-vannes",
    extremites: ["les-vanniers", "relais-des-vannes"],
    originesAutorisees: ["les-vanniers"],
    libellesDOptions: LIBELLES_D_OPTIONS_DES_NACELLES,
    dureeSecondes: 300,
    etatInitial: "praticable",
    consommationConnue: {
      stock: "combustible",
      quantite: 2,
      unite: "litres",
    },
    consommationIncertaine: {
      stock: "eau",
      minimum: 2,
      maximum: 4,
      quantiteReelle: 3,
      unite: "litres",
      renseignementId: "nacelles-releve-de-branche",
    },
    renseignements: RENSEIGNEMENTS_NACELLES.map((renseignement) => ({
      ...renseignement,
      tronconId: "chenal-des-vannes",
    })),
  },
  {
    id: "nacelles-de-veille-basse",
    extremites: ["haut-puits", "veille-basse"],
    libellesDOptions: LIBELLES_D_OPTIONS_DES_NACELLES,
    dureeSecondes: 360,
    etatInitial: "degrade",
    consommationConnue: {
      stock: "combustible",
      quantite: 6,
      unite: "litres",
    },
    consommationIncertaine: {
      stock: "eau",
      minimum: 6,
      maximum: 12,
      quantiteReelle: 8,
      unite: "litres",
      renseignementId: "nacelles-releve-de-branche",
    },
    renseignements: RENSEIGNEMENTS_NACELLES.map((renseignement) => ({
      ...renseignement,
      tronconId: "nacelles-de-veille-basse",
    })),
  },
  {
    id: "chemin-de-l-hospice",
    extremites: ["veille-basse", "hospice-du-sillon"],
    originesAutorisees: ["veille-basse"],
    dureeSecondes: 300,
    etatInitial: "praticable",
    consommationConnue: {
      stock: "combustible",
      quantite: 3,
      unite: "litres",
    },
    consommationIncertaine: {
      stock: "eau",
      minimum: 3,
      maximum: 5,
      quantiteReelle: 4,
      unite: "litres",
      renseignementId: "hospice-releve-branche-basse",
    },
    renseignements: [
      {
        ...RENSEIGNEMENT_D_APPROCHE_DU_DEVERSOIR,
        id: "hospice-releve-branche-basse",
        tronconId: "chemin-de-l-hospice",
        source: "techniciens-de-veille-basse",
        etatAnnonce: "praticable",
        libelles: {
          fr: {
            source: "Techniciens de Veille-Basse",
            danger: "Sas étroits sous une cendre filtrée",
            controlePolitique: "Relais tenu par l’Hospice du Sillon",
          },
          en: {
            source: "Lower Watch technicians",
            danger: "Narrow airlocks under filtered ash",
            controlePolitique: "Relay held by Sillon Hospice",
          },
        },
      },
    ],
  },
  {
    id: "chenal-de-l-hospice",
    extremites: ["hospice-du-sillon", "relais-des-vannes"],
    originesAutorisees: ["hospice-du-sillon"],
    dureeSecondes: 360,
    etatInitial: "degrade",
    consommationConnue: {
      stock: "combustible",
      quantite: 4,
      unite: "litres",
    },
    consommationIncertaine: {
      stock: "eau",
      minimum: 4,
      maximum: 7,
      quantiteReelle: 5,
      unite: "litres",
      renseignementId: "hospice-releve-aval",
    },
    renseignements: [
      {
        ...RENSEIGNEMENT_D_APPROCHE_DU_DEVERSOIR,
        id: "hospice-releve-aval",
        tronconId: "chenal-de-l-hospice",
        source: "relais-de-l-hospice",
        etatAnnonce: "degrade",
        libelles: {
          fr: {
            source: "Relais filtré de l’Hospice",
            danger: "Canal bas encombré de filtres usés",
            controlePolitique: "Passage garanti par l’Hospice",
          },
          en: {
            source: "Hospice filtered relay",
            danger: "Low canal cluttered with spent filters",
            controlePolitique: "Passage guaranteed by the Hospice",
          },
        },
      },
    ],
  },
  {
    id: "conduite-du-deversoir",
    extremites: ["relais-des-vannes", "deversoir-noir"],
    originesAutorisees: ["relais-des-vannes"],
    dureeSecondes: 360,
    etatInitial: "praticable",
    consommationConnue: {
      stock: "combustible",
      quantite: 4,
      unite: "litres",
    },
    consommationIncertaine: {
      stock: "eau",
      minimum: 4,
      maximum: 6,
      quantiteReelle: 5,
      unite: "litres",
      renseignementId: "approche-du-deversoir",
    },
    renseignements: [
      {
        ...RENSEIGNEMENT_D_APPROCHE_DU_DEVERSOIR,
        tronconId: "conduite-du-deversoir",
      },
    ],
  },
  {
    id: "passage-de-la-ligne-zero",
    nom: {
      fr: "Passage de la Ligne Zéro",
      en: "Zero Line Passage",
    },
    extremites: ["deversoir-noir", "lisiere-trame-de-fer"],
    originesAutorisees: ["deversoir-noir"],
    dureeSecondes: 480,
    etatInitial: "praticable",
    consommationConnue: {
      stock: "combustible",
      quantite: 4,
      unite: "litres",
    },
    consommationIncertaine: {
      stock: "eau",
      minimum: 4,
      maximum: 6,
      quantiteReelle: 5,
      unite: "litres",
      renseignementId: "ligne-zero-passage",
    },
    renseignements: [
      {
        ...RENSEIGNEMENT_DE_LA_LIGNE_ZERO,
        tronconId: "passage-de-la-ligne-zero",
      },
    ],
  },
  {
    id: "piste-des-levees",
    nom: {
      fr: "Piste des levées",
      en: "Embankment Track",
    },
    extremites: ["deversoir-noir", "lisiere-trame-de-fer"],
    originesAutorisees: ["deversoir-noir"],
    dureeSecondes: 540,
    etatInitial: "degrade",
    consommationConnue: {
      stock: "combustible",
      quantite: 7,
      unite: "litres",
    },
    consommationIncertaine: {
      stock: "eau",
      minimum: 8,
      maximum: 10,
      quantiteReelle: 9,
      unite: "litres",
      renseignementId: "levees-releve-deversoir",
    },
    renseignements: [
      {
        ...RENSEIGNEMENT_D_APPROCHE_DU_DEVERSOIR,
        id: "levees-releve-deversoir",
        tronconId: "piste-des-levees",
        source: "techniciens-du-deversoir",
        etatAnnonce: "degrade",
        libelles: {
          fr: {
            source: "Relevé de surface des techniciens du Déversoir",
            danger: "Levées instables sous la tempête de cendre",
            controlePolitique: "Passage extérieur au Conseil des Vannes",
          },
          en: {
            source: "Spillway technicians’ surface survey",
            danger: "Unstable embankments beneath the ash storm",
            controlePolitique: "Passage outside the Sluice Council",
          },
        },
      },
    ],
  },
  {
    id: "rampe-de-barriere-neuve",
    nom: {
      fr: "Rampe de Barrière-Neuve",
      en: "New Barrier Ramp",
    },
    extremites: ["lisiere-trame-de-fer", "barriere-neuve"],
    originesAutorisees: ["lisiere-trame-de-fer"],
    dureeSecondes: 420,
    etatInitial: "praticable",
    consommationConnue: {
      stock: "combustible",
      quantite: 4,
      unite: "litres",
    },
    consommationIncertaine: {
      stock: "eau",
      minimum: 4,
      maximum: 6,
      quantiteReelle: 5,
      unite: "litres",
      renseignementId: "barriere-neuve-controle",
    },
    renseignements: [
      {
        id: "barriere-neuve-controle",
        tronconId: "rampe-de-barriere-neuve",
        source: "douaniers-du-rail",
        releveA: 0,
        fiabilite: "confirme",
        etatAnnonce: "praticable",
        meteo: "cendre-basse",
        panache: "absent",
        danger: "controle-des-essieux",
        controlePolitique: "republique-du-rail",
        libelles: {
          fr: {
            source: "Avis officiel de Barrière-Neuve",
            danger: "Contrôle des essieux et des charges",
            controlePolitique: "Voie principale tenue par la République du Rail",
          },
          en: {
            source: "New Barrier official notice",
            danger: "Axle and load inspection",
            controlePolitique: "Main route held by the Rail Republic",
          },
        },
      },
    ],
  },
  {
    id: "voie-des-ponts-lourds",
    nom: {
      fr: "Voie des Ponts lourds",
      en: "Heavy Bridges Route",
    },
    extremites: ["barriere-neuve", "grand-aiguillage"],
    originesAutorisees: ["barriere-neuve"],
    dureeSecondes: 600,
    etatInitial: "degrade",
    consommationConnue: {
      stock: "combustible",
      quantite: 6,
      unite: "litres",
    },
    consommationIncertaine: {
      stock: "eau",
      minimum: 6,
      maximum: 9,
      quantiteReelle: 8,
      unite: "litres",
      renseignementId: "ponts-lourds-aiguilleurs",
    },
    renseignements: [
      {
        id: "ponts-lourds-aiguilleurs",
        tronconId: "voie-des-ponts-lourds",
        source: "aiguilleurs",
        releveA: 0,
        fiabilite: "rapporte",
        etatAnnonce: "degrade",
        meteo: "rafales-de-cendre",
        panache: "incertain",
        danger: "ponts-fatigues",
        controlePolitique: "republique-du-rail",
        libelles: {
          fr: {
            source: "Aiguilleurs de Grand-Aiguillage",
            danger: "Ponts lourds fatigués mais entretenus",
            controlePolitique: "Services et réquisitions de la République du Rail",
          },
          en: {
            source: "Grand Junction switch crews",
            danger: "Worn but maintained heavy bridges",
            controlePolitique: "Rail Republic services and requisitions",
          },
        },
      },
    ],
  },
  {
    id: "embranchement-de-pompe-neuve",
    nom: {
      fr: "Embranchement de Pompe-Neuve",
      en: "New Pump Branch",
    },
    extremites: ["lisiere-trame-de-fer", "pompe-neuve"],
    originesAutorisees: ["lisiere-trame-de-fer"],
    dureeSecondes: 510,
    etatInitial: "degrade",
    consommationConnue: {
      stock: "combustible",
      quantite: 5,
      unite: "litres",
    },
    consommationIncertaine: {
      stock: "eau",
      minimum: 5,
      maximum: 9,
      quantiteReelle: 7,
      unite: "litres",
      renseignementId: "pompe-neuve-balises-libres",
    },
    renseignements: [
      {
        id: "pompe-neuve-balises-libres",
        tronconId: "embranchement-de-pompe-neuve",
        source: "mecaniciens-pompe-neuve",
        releveA: 0,
        fiabilite: "rapporte",
        etatAnnonce: "degrade",
        meteo: "cendre-basse",
        panache: "incertain",
        danger: "aiguilles-sans-garde",
        controlePolitique: "puits-libres",
        libelles: {
          fr: {
            source: "Balises reprises par les mécaniciens de Pompe-Neuve",
            danger: "Aiguilles sans garde, état variable après chaque convoi",
            controlePolitique: "Embranchement autonome soutenu par les Puits Libres",
          },
          en: {
            source: "Markers restored by New Pump mechanics",
            danger: "Unattended switches, condition varies after each convoy",
            controlePolitique: "Autonomous branch supported by the Free Wells",
          },
        },
      },
    ],
  },
  {
    id: "galerie-des-reservoirs",
    nom: {
      fr: "Galerie des Réservoirs",
      en: "Reservoir Gallery",
    },
    extremites: ["pompe-neuve", "traverse-libre"],
    originesAutorisees: ["pompe-neuve"],
    dureeSecondes: 660,
    etatInitial: "degrade",
    consommationConnue: {
      stock: "combustible",
      quantite: 6,
      unite: "litres",
    },
    consommationIncertaine: {
      stock: "eau",
      minimum: 7,
      maximum: 11,
      quantiteReelle: 9,
      unite: "litres",
      renseignementId: "traverse-libre-affaissement",
    },
    renseignements: [
      {
        id: "traverse-libre-affaissement",
        tronconId: "galerie-des-reservoirs",
        source: "eclaireurs-puits-libres",
        releveA: 0,
        fiabilite: "ancien",
        etatAnnonce: "degrade",
        meteo: "rafales-de-cendre",
        panache: "incertain",
        danger: "galerie-affaissee",
        controlePolitique: "puits-libres",
        libelles: {
          fr: {
            source: "Dernier relevé partagé par les éclaireurs des Puits Libres",
            danger: "Affaissement signalé, détour coûteux encore praticable",
            controlePolitique: "Passage collectif sans garantie centralisée",
          },
          en: {
            source: "Last survey shared by Free Wells scouts",
            danger: "Reported collapse, costly detour still passable",
            controlePolitique: "Collective passage without centralized guarantee",
          },
        },
      },
    ],
  },
  {
    id: "rocade-du-marche",
    nom: {
      fr: "Rocade du Marché",
      en: "Market Loop",
    },
    extremites: ["grand-aiguillage", "marche-des-traverses"],
    originesAutorisees: ["grand-aiguillage"],
    dureeSecondes: 540,
    etatInitial: "praticable",
    consommationConnue: {
      stock: "combustible",
      quantite: 5,
      unite: "litres",
    },
    consommationIncertaine: {
      stock: "eau",
      minimum: 4,
      maximum: 7,
      quantiteReelle: 6,
      unite: "litres",
      renseignementId: "marche-controle-republicain",
    },
    renseignements: [
      {
        id: "marche-controle-republicain",
        tronconId: "rocade-du-marche",
        source: "commis-du-marche",
        releveA: 0,
        fiabilite: "confirme",
        etatAnnonce: "praticable",
        meteo: "cendre-basse",
        panache: "absent",
        danger: "pesage-obligatoire",
        controlePolitique: "republique-du-rail",
        libelles: {
          fr: {
            source: "Registre officiel des commis du Marché",
            danger: "Pesage obligatoire des convois et des pièces",
            controlePolitique: "Accès officiel garanti par la République du Rail",
          },
          en: {
            source: "Sleeper Market clerks’ official register",
            danger: "Mandatory weighing of convoys and parts",
            controlePolitique: "Official access guaranteed by the Rail Republic",
          },
        },
      },
    ],
  },
  {
    id: "voie-des-citernes",
    nom: {
      fr: "Voie des Citernes",
      en: "Cistern Track",
    },
    extremites: ["traverse-libre", "marche-des-traverses"],
    originesAutorisees: ["traverse-libre"],
    dureeSecondes: 600,
    etatInitial: "degrade",
    consommationConnue: {
      stock: "combustible",
      quantite: 5,
      unite: "litres",
    },
    consommationIncertaine: {
      stock: "eau",
      minimum: 5,
      maximum: 9,
      quantiteReelle: 7,
      unite: "litres",
      renseignementId: "marche-porteurs-libres",
    },
    renseignements: [
      {
        id: "marche-porteurs-libres",
        tronconId: "voie-des-citernes",
        source: "porteurs-des-puits-libres",
        releveA: 0,
        fiabilite: "rapporte",
        etatAnnonce: "degrade",
        meteo: "rafales-de-cendre",
        panache: "incertain",
        danger: "traverses-disjointes",
        controlePolitique: "puits-libres",
        libelles: {
          fr: {
            source: "Relevé des porteurs des Puits Libres",
            danger: "Traverses disjointes et balises déplacées",
            controlePolitique: "Accès autonome sans garantie de manifeste",
          },
          en: {
            source: "Free Wells carriers’ survey",
            danger: "Separated sleepers and displaced markers",
            controlePolitique: "Autonomous access without manifest guarantee",
          },
        },
      },
    ],
  },
  {
    id: "ligne-du-signal-zero",
    nom: {
      fr: "Ligne de Signal-Zéro",
      en: "Zero Signal Line",
    },
    extremites: ["marche-des-traverses", "signal-zero"],
    originesAutorisees: ["marche-des-traverses"],
    dureeSecondes: 480,
    etatInitial: "praticable",
    consommationConnue: {
      stock: "combustible",
      quantite: 4,
      unite: "litres",
    },
    consommationIncertaine: {
      stock: "eau",
      minimum: 3,
      maximum: 6,
      quantiteReelle: 5,
      unite: "litres",
      renseignementId: "signal-zero-techniciens",
    },
    renseignements: [
      {
        id: "signal-zero-techniciens",
        tronconId: "ligne-du-signal-zero",
        source: "techniciens-signal-zero",
        releveA: 0,
        fiabilite: "confirme",
        etatAnnonce: "praticable",
        meteo: "cendre-basse",
        panache: "absent",
        danger: "signaux-doubles",
        controlePolitique: "enclave-technique",
        libelles: {
          fr: {
            source: "Relève commune des techniciens de Signal-Zéro",
            danger: "Signaux doubles, aucun itinéraire imposé",
            controlePolitique: "Enclave technique ouverte aux deux axes",
          },
          en: {
            source: "Joint survey by Zero Signal technicians",
            danger: "Double signals with no mandated route",
            controlePolitique: "Technical enclave open to both axes",
          },
        },
      },
    ],
  },
  {
    id: "voie-des-contremaitres",
    nom: {
      fr: "Voie des Contremaîtres",
      en: "Foremen’s Track",
    },
    extremites: ["marche-des-traverses", "barriere-neuve"],
    originesAutorisees: ["marche-des-traverses"],
    engagementsPrealables: [
      {
        tronconId: "voie-des-citernes",
        destination: "marche-des-traverses",
      },
    ],
    dureeSecondes: 540,
    etatInitial: "degrade",
    consommationConnue: {
      stock: "combustible",
      quantite: 5,
      unite: "litres",
    },
    consommationIncertaine: {
      stock: "eau",
      minimum: 4,
      maximum: 8,
      quantiteReelle: 6,
      unite: "litres",
      renseignementId: "contremaitres-vers-barriere",
    },
    renseignements: [
      {
        id: "contremaitres-vers-barriere",
        tronconId: "voie-des-contremaitres",
        source: "commis-du-marche",
        releveA: 0,
        fiabilite: "rapporte",
        etatAnnonce: "degrade",
        meteo: "cendre-basse",
        panache: "absent",
        danger: "convois-de-service",
        controlePolitique: "republique-du-rail",
        libelles: {
          fr: {
            source: "Carnet aval des contremaîtres du Marché",
            danger: "Convois de service et aiguilles à contretemps",
            controlePolitique: "Retour aval vers Barrière-Neuve sous contrôle du Rail",
          },
          en: {
            source: "Sleeper Market foremen’s downstream log",
            danger: "Service trains and mistimed switches",
            controlePolitique: "Downstream access to New Barrier under Rail control",
          },
        },
      },
    ],
  },
  {
    id: "traverse-des-porteurs",
    nom: {
      fr: "Traverse des Porteurs",
      en: "Carriers’ Crossing",
    },
    extremites: ["marche-des-traverses", "pompe-neuve"],
    originesAutorisees: ["marche-des-traverses"],
    engagementsPrealables: [
      {
        tronconId: "rocade-du-marche",
        destination: "marche-des-traverses",
      },
    ],
    dureeSecondes: 600,
    etatInitial: "degrade",
    consommationConnue: {
      stock: "combustible",
      quantite: 5,
      unite: "litres",
    },
    consommationIncertaine: {
      stock: "eau",
      minimum: 5,
      maximum: 9,
      quantiteReelle: 7,
      unite: "litres",
      renseignementId: "porteurs-vers-pompe",
    },
    renseignements: [
      {
        id: "porteurs-vers-pompe",
        tronconId: "traverse-des-porteurs",
        source: "porteurs-des-puits-libres",
        releveA: 0,
        fiabilite: "rapporte",
        etatAnnonce: "degrade",
        meteo: "rafales-de-cendre",
        panache: "incertain",
        danger: "balises-mobiles",
        controlePolitique: "puits-libres",
        libelles: {
          fr: {
            source: "Relève aval des porteurs du Marché",
            danger: "Balises mobiles et traverses couvertes de cendre",
            controlePolitique: "Connexion aval autonome vers Pompe-Neuve",
          },
          en: {
            source: "Sleeper Market carriers’ downstream survey",
            danger: "Moving markers and ash-covered sleepers",
            controlePolitique: "Autonomous downstream link to New Pump",
          },
        },
      },
    ],
  },
  {
    id: "rocade-des-regulateurs",
    nom: {
      fr: "Rocade des Régulateurs",
      en: "Regulators’ Loop",
    },
    extremites: ["grand-aiguillage", "signal-zero"],
    originesAutorisees: ["grand-aiguillage"],
    engagementsPrealables: [
      {
        tronconId: "voie-des-contremaitres",
        destination: "barriere-neuve",
      },
      {
        tronconId: "voie-des-ponts-lourds",
        destination: "grand-aiguillage",
      },
    ],
    dureeSecondes: 600,
    etatInitial: "praticable",
    consommationConnue: {
      stock: "combustible",
      quantite: 6,
      unite: "litres",
    },
    consommationIncertaine: {
      stock: "eau",
      minimum: 5,
      maximum: 8,
      quantiteReelle: 7,
      unite: "litres",
      renseignementId: "regulateurs-vers-signal",
    },
    renseignements: [
      {
        id: "regulateurs-vers-signal",
        tronconId: "rocade-des-regulateurs",
        source: "aiguilleurs",
        releveA: 0,
        fiabilite: "confirme",
        etatAnnonce: "praticable",
        meteo: "cendre-basse",
        panache: "absent",
        danger: "gabarit-de-la-piece",
        controlePolitique: "republique-du-rail",
        libelles: {
          fr: {
            source: "Table de marche des aiguilleurs de Grand-Aiguillage",
            danger: "Gabarit limité par le transport de la Pièce",
            controlePolitique: "Sortie technique vers Signal-Zéro",
          },
          en: {
            source: "Grand Junction switch crews’ running table",
            danger: "Clearance limited by transport of the Part",
            controlePolitique: "Technical exit toward Zero Signal",
          },
        },
      },
    ],
  },
  {
    id: "derivation-des-puits",
    nom: {
      fr: "Dérivation des Puits",
      en: "Wells Diversion",
    },
    extremites: ["traverse-libre", "signal-zero"],
    originesAutorisees: ["traverse-libre"],
    engagementsPrealables: [
      {
        tronconId: "traverse-des-porteurs",
        destination: "pompe-neuve",
      },
      {
        tronconId: "galerie-des-reservoirs",
        destination: "traverse-libre",
      },
    ],
    dureeSecondes: 660,
    etatInitial: "degrade",
    consommationConnue: {
      stock: "combustible",
      quantite: 6,
      unite: "litres",
    },
    consommationIncertaine: {
      stock: "eau",
      minimum: 6,
      maximum: 10,
      quantiteReelle: 8,
      unite: "litres",
      renseignementId: "puits-vers-signal",
    },
    renseignements: [
      {
        id: "puits-vers-signal",
        tronconId: "derivation-des-puits",
        source: "eclaireurs-puits-libres",
        releveA: 0,
        fiabilite: "rapporte",
        etatAnnonce: "degrade",
        meteo: "rafales-de-cendre",
        panache: "incertain",
        danger: "galeries-sans-manifeste",
        controlePolitique: "puits-libres",
        libelles: {
          fr: {
            source: "Relevé des éclaireurs de Traverse-Libre",
            danger: "Galeries sans manifeste et réserves éloignées",
            controlePolitique: "Sortie autonome vers Signal-Zéro",
          },
          en: {
            source: "Free Crossing scouts’ survey",
            danger: "Unmanifested galleries and distant reserves",
            controlePolitique: "Autonomous exit toward Zero Signal",
          },
        },
      },
    ],
  },
  {
    id: "faisceau-de-l-aiguillage-zero",
    nom: {
      fr: "Faisceau de l’Aiguillage Zéro",
      en: "Zero Junction Fan",
    },
    extremites: ["signal-zero", "aiguillage-zero"],
    originesAutorisees: ["signal-zero"],
    dureeSecondes: 540,
    etatInitial: "praticable",
    consommationConnue: {
      stock: "combustible",
      quantite: 5,
      unite: "litres",
    },
    consommationIncertaine: {
      stock: "eau",
      minimum: 4,
      maximum: 7,
      quantiteReelle: 6,
      unite: "litres",
      renseignementId: "aiguillage-zero-faisceau",
    },
    renseignements: [
      {
        id: "aiguillage-zero-faisceau",
        tronconId: "faisceau-de-l-aiguillage-zero",
        source: "techniciens-signal-zero",
        releveA: 0,
        fiabilite: "confirme",
        etatAnnonce: "praticable",
        meteo: "cendre-basse",
        panache: "absent",
        danger: "signaux-doubles",
        controlePolitique: "enclave-technique",
        libelles: {
          fr: {
            source: "Table commune de Signal-Zéro",
            danger: "Quatre voies convergent sur un unique cœur mobile",
            controlePolitique: "Accès ouvert aux délégations des deux axes",
          },
          en: {
            source: "Zero Signal joint running table",
            danger: "Four tracks converge on a single mobile heart",
            controlePolitique: "Access open to delegations from both axes",
          },
        },
      },
    ],
  },
  {
    id: "passage-de-la-couronne-muette",
    nom: {
      fr: "Passage de la Couronne muette",
      en: "Silent Crown Passage",
    },
    extremites: ["aiguillage-zero", "couronne-muette"],
    originesAutorisees: ["aiguillage-zero"],
    dureeSecondes: 660,
    etatInitial: "praticable",
    consommationConnue: {
      stock: "combustible",
      quantite: 6,
      unite: "litres",
    },
    consommationIncertaine: {
      stock: "eau",
      minimum: 5,
      maximum: 8,
      quantiteReelle: 7,
      unite: "litres",
      renseignementId: "couronne-muette-passage",
    },
    renseignements: [
      {
        id: "couronne-muette-passage",
        tronconId: "passage-de-la-couronne-muette",
        source: "techniciens-signal-zero",
        releveA: 0,
        fiabilite: "confirme",
        etatAnnonce: "praticable",
        meteo: "rafales-de-cendre",
        panache: "incertain",
        danger: "gabarit-de-la-piece",
        controlePolitique: "sans-controle-etabli",
        libelles: {
          fr: {
            source: "Registre de sortie du Conseil de l’Aiguillage",
            danger: "Verrouillage définitif des voies arrière après le passage",
            controlePolitique: "Décision commune consignée avant la Couronne",
          },
          en: {
            source: "Junction Council exit register",
            danger: "Rear tracks lock permanently after passage",
            controlePolitique: "Joint decision recorded before the Crown",
          },
        },
      },
    ],
  },
  {
    id: "voie-de-tete-de-ligne",
    nom: {
      fr: "Voie de Tête-de-Ligne",
      en: "Railhead Line",
    },
    extremites: ["couronne-muette", "tete-de-ligne"],
    originesAutorisees: ["couronne-muette"],
    dureeSecondes: 600,
    etatInitial: "praticable",
    consommationConnue: {
      stock: "combustible",
      quantite: 6,
      unite: "litres",
    },
    consommationIncertaine: {
      stock: "eau",
      minimum: 5,
      maximum: 8,
      quantiteReelle: 7,
      unite: "litres",
      renseignementId: "tete-de-ligne-approche",
    },
    renseignements: [
      {
        id: "tete-de-ligne-approche",
        tronconId: "voie-de-tete-de-ligne",
        source: "aiguilleurs",
        releveA: 0,
        fiabilite: "rapporte",
        etatAnnonce: "praticable",
        meteo: "cendre-basse",
        panache: "absent",
        danger: "ponts-fatigues",
        controlePolitique: "republique-du-rail",
        libelles: {
          fr: {
            source: "Table de marche de la République du Rail",
            danger: "Ponts fortifiés sous charge permanente",
            controlePolitique: "Camp retranché de Tête-de-Ligne",
          },
          en: {
            source: "Rail Republic running table",
            danger: "Fortified bridges under permanent load",
            controlePolitique: "Railhead’s entrenched camp",
          },
        },
      },
      {
        id: "tete-de-ligne-charte",
        tronconId: "voie-de-tete-de-ligne",
        source: "aiguilleurs",
        releveA: 0,
        fiabilite: "confirme",
        etatAnnonce: "praticable",
        meteo: "cendre-basse",
        panache: "absent",
        danger: "ponts-fatigues",
        controlePolitique: "passage-conteste",
        libelles: {
          fr: {
            source: "Copie du registre portée par la délégation des Puits Libres",
            danger: "La Charte ou l’Engagement autonome conteste l’exclusivité du quai",
            controlePolitique: "Atelier commun recevable comme concession publique",
          },
          en: {
            source: "Register copy carried by the Free Wells delegation",
            danger: "The Charter or autonomous Commitment challenges platform exclusivity",
            controlePolitique: "Shared workshop admissible as a public concession",
          },
        },
      },
      {
        id: "tete-de-ligne-trace",
        tronconId: "voie-de-tete-de-ligne",
        source: "aiguilleurs",
        releveA: 0,
        fiabilite: "rapporte",
        etatAnnonce: "degrade",
        meteo: "rafales-de-cendre",
        panache: "incertain",
        danger: "controle-des-essieux",
        controlePolitique: "republique-du-rail",
        libelles: {
          fr: {
            source: "Inventaire contradictoire de l’Aiguillage Zéro",
            danger: "La Trace du vol ferme le mandat républicain",
            controlePolitique: "Seul l’atelier commun reste concédable",
          },
          en: {
            source: "Disputed Zero Junction inventory",
            danger: "The theft Trace closes the Republic mandate",
            controlePolitique: "Only the shared workshop remains grantable",
          },
        },
      },
    ],
  },
  {
    id: "chemin-des-trois-veilles",
    nom: {
      fr: "Chemin des Trois Veilles",
      en: "Three Watches Path",
    },
    extremites: ["couronne-muette", "veille-des-trois"],
    originesAutorisees: ["couronne-muette"],
    dureeSecondes: 660,
    etatInitial: "degrade",
    consommationConnue: {
      stock: "combustible",
      quantite: 7,
      unite: "litres",
    },
    consommationIncertaine: {
      stock: "eau",
      minimum: 6,
      maximum: 9,
      quantiteReelle: 8,
      unite: "litres",
      renseignementId: "veille-des-trois-approche",
    },
    renseignements: [
      {
        id: "veille-des-trois-approche",
        tronconId: "chemin-des-trois-veilles",
        source: "relais-des-pelerins",
        releveA: 0,
        fiabilite: "rapporte",
        etatAnnonce: "degrade",
        meteo: "rafales-de-cendre",
        panache: "incertain",
        danger: "visibilite",
        controlePolitique: "pelerins-de-cendre",
        libelles: {
          fr: {
            source: "Relevé des gardiens des Trois Veilles",
            danger: "Balises mortes et cendre réfléchissante",
            controlePolitique: "Sanctuaire technique des Pèlerins de Cendre",
          },
          en: {
            source: "Three Watches keepers’ survey",
            danger: "Dead beacons and reflective ash",
            controlePolitique: "Ash Pilgrims’ technical sanctuary",
          },
        },
      },
      {
        id: "veille-des-trois-registres",
        tronconId: "chemin-des-trois-veilles",
        source: "relais-des-pelerins",
        releveA: 0,
        fiabilite: "confirme",
        etatAnnonce: "degrade",
        meteo: "rafales-de-cendre",
        panache: "incertain",
        danger: "visibilite",
        controlePolitique: "pelerins-de-cendre",
        libelles: {
          fr: {
            source: "Copies des registres de Veille-Basse",
            danger: "Les mesures anciennes peuvent être séparées des ajouts récents",
            controlePolitique: "Renforcement du sanctuaire documenté comme concession",
          },
          en: {
            source: "Low Watch register copies",
            danger: "Old measurements can be separated from recent additions",
            controlePolitique: "Sanctuary reinforcement documented as a concession",
          },
        },
      },
      {
        id: "veille-des-trois-repli",
        tronconId: "chemin-des-trois-veilles",
        source: "relais-des-pelerins",
        releveA: 0,
        fiabilite: "rapporte",
        etatAnnonce: "degrade",
        meteo: "rafales-de-cendre",
        panache: "incertain",
        danger: "visibilite",
        controlePolitique: "pelerins-de-cendre",
        libelles: {
          fr: {
            source: "Message de repli de Veille-Basse",
            danger: "Aucun gardien stable ne peut tenir trois balises",
            controlePolitique: "L’évacuation des relevés devient la seule concession sûre",
          },
          en: {
            source: "Low Watch withdrawal message",
            danger: "No stable keepers can hold three beacons",
            controlePolitique: "Evacuating the surveys becomes the only safe concession",
          },
        },
      },
    ],
  },
  {
    id: "piste-des-serres-de-verre",
    nom: {
      fr: "Piste des Serres-de-Verre",
      en: "Glasshouses Track",
    },
    extremites: ["couronne-muette", "serres-de-verre"],
    originesAutorisees: ["couronne-muette"],
    dureeSecondes: 720,
    etatInitial: "degrade",
    consommationConnue: {
      stock: "combustible",
      quantite: 7,
      unite: "litres",
    },
    consommationIncertaine: {
      stock: "eau",
      minimum: 7,
      maximum: 10,
      quantiteReelle: 9,
      unite: "litres",
      renseignementId: "serres-de-verre-ralliement",
    },
    renseignements: [
      {
        id: "serres-de-verre-ralliement",
        tronconId: "piste-des-serres-de-verre",
        source: "eclaireurs-puits-libres",
        releveA: 0,
        fiabilite: "rapporte",
        etatAnnonce: "degrade",
        meteo: "rafales-de-cendre",
        panache: "incertain",
        danger: "orniere",
        controlePolitique: "sans-controle-etabli",
        libelles: {
          fr: {
            source: "Rapports croisés des quatre Colonies quittées",
            danger: "Verrières effondrées et piste gourmande en eau",
            controlePolitique: "Ralliement composite sans autorité unique",
          },
          en: {
            source: "Cross-checked reports from the four departed Colonies",
            danger: "Collapsed glass roofs and a water-hungry track",
            controlePolitique: "Composite rally under no single authority",
          },
        },
      },
    ],
  },
  {
    id: "rampe-du-seuil",
    nom: {
      fr: "Rampe du Seuil",
      en: "Threshold Ramp",
    },
    extremites: ["serres-de-verre", "seuil"],
    originesAutorisees: ["serres-de-verre"],
    dureeSecondes: 540,
    etatInitial: "degrade",
    consommationConnue: {
      stock: "combustible",
      quantite: 5,
      unite: "litres",
    },
    consommationIncertaine: {
      stock: "eau",
      minimum: 5,
      maximum: 8,
      quantiteReelle: 7,
      unite: "litres",
      renseignementId: "seuil-rampe-logistique",
    },
    renseignements: [
      {
        id: "seuil-rampe-logistique",
        tronconId: "rampe-du-seuil",
        source: "eclaireurs-puits-libres",
        releveA: 0,
        fiabilite: "confirme",
        etatAnnonce: "degrade",
        meteo: "cendre-basse",
        panache: "absent",
        danger: "ponts-fatigues",
        controlePolitique: "passage-conteste",
        libelles: {
          fr: {
            source: "Relevé commun des équipes ralliées aux Serres",
            danger: "Rampe brisée exigeant eau, pièces et équipes coordonnées",
            controlePolitique: "Le Seuil revendique la maîtrise de son accès",
          },
          en: {
            source: "Joint survey by the teams rallied at the Glasshouses",
            danger: "Broken ramp requiring water, parts, and coordinated crews",
            controlePolitique: "Threshold claims authority over its own access",
          },
        },
      },
    ],
  },
] as const;
