// Ce fichier est généré par npm run content:compile.
export default {
  "version": 1,
  "fragments": [
    "/api/commercial/assets/haut-puits-decanteur.webp",
    "/api/commercial/assets/haut-puits-ilyana.webp",
    "/api/commercial/assets/haut-puits-vanniers.webp",
    "/api/commercial/assets/nacelles-compagnes.webp",
    "/api/commercial/assets/nacelles-deux-rives.webp",
    "/api/commercial/assets/nacelles-frein.webp",
    "/api/commercial/assets/nacelles-trace.webp",
    "/api/commercial/assets/veille-basse-archives.webp",
    "/api/commercial/assets/veille-basse-cohorte.webp",
    "/api/commercial/assets/veille-basse-maelys.webp",
    "/api/commercial/assets/veille-basse-porte.webp",
    "2 teams integrated",
    "2 équipes intégrées",
    "A gloved hand hesitates above the open magnetic brake while bright brass filings fall onto a survey cloth.",
    "A hand on the brake",
    "Accord des Puits Libres et des Pèlerins",
    "Across the table, every old curve converges on the same sacrificed territories.",
    "Adapt the airlocks for the Ark for the Displaced",
    "Adapter les sas pour l’Arche des déplacés",
    "Affecter les techniciens au renfort du sas",
    "Afflux de déplacés",
    "Aide reçue",
    "An ash gust strains the outer airlock. Lower Watch is warned: without intervention, its two teams cannot maintain the filters, archives, and welcome at the same time.",
    "Applied Cohort support: sealed-frame counterweight",
    "Applied Faction support: priority shared cage",
    "Applied Hospice support: filtered relay from the lower branch",
    "Applied support: main winch under controlled load",
    "Appui appliqué : treuil principal sous charge contrôlée",
    "Appui appliqué par la Cohorte : contrepoids de charpente étanche",
    "Appui appliqué par les Factions : cage commune prioritaire",
    "Appui appliqué par l’Hospice : relais filtré de la branche basse",
    "Arbitrage collectif du registre maintenu",
    "Arche des déplacés",
    "Arche des déplacés documentée",
    "Arche des déplacés — possibilité à étudier",
    "Archive room without readable text: engraved maps, conduits, and calibration drums show ash displaced from central lighthouses toward peripheral Basins.",
    "Archives opened — ash displacement documented",
    "Archives ouvertes — déplacement des cendres documenté",
    "Archives scellées",
    "Archives sealed",
    "Archives techniques de Veille-Basse",
    "Ark for the Displaced documented",
    "Around the deep cistern valve, Free Wells delegates and displaced families await the Lantern-Bearer’s decision.",
    "Ash-coated reed baskets mark the drift all the way to the suspended workshops.",
    "Assign the technicians to reinforce the airlock",
    "At Lower Watch",
    "Atelier de Veille-Basse",
    "Aucun engagement diplomatique.",
    "Aucune décision",
    "Aucune transformation imposée.",
    "Autonomie de Haut-Puits garantie",
    "Autonomie hydrique menacée",
    "Autour de la vanne de la citerne profonde, les délégués des Puits Libres et les familles déplacées attendent la décision du Porte-Lanterne.",
    "Backflow records copied",
    "Baliser le boîtier et ses témoins",
    "Basketmakers’ Path",
    "Beneath a cable drum, technicians discover an old magnetic brake connected to a brass plate and mark it without touching it.",
    "Beneath the dead tower, every free bunk already has a name; the choice is which community will carry the newcomers.",
    "Beneath the main drum, an Ancient Network magnetic brake still modulates every load. Its pulses match the registers showing ash historically displaced toward the outskirts.",
    "Both approach registers remain open side by side: no delegate can erase the opposite bank.",
    "Both projects require an entire chassis and remain incompatible with a free or instant transformation.",
    "Boues du panache confinées",
    "Bring common maintenance before the Sluice Council",
    "Bring shared passage before the Sluice Council",
    "Cable brake covertly altered",
    "Cable brake publicly retuned",
    "Cable crews appointed by both branches",
    "Cable crews’ mandate unrecognized",
    "Cable crossing reserved",
    "Cableway Magnetic Brake",
    "Cableway Relay",
    "Calibration maps show that the Ancient Network protected productive cities and pushed ash toward the Fractured Basins. Its loss of synchronization did not create the mass: it released what the peripheries had always received.",
    "Camp des Digues",
    "Caravan-city",
    "Ce choix se tranche dans l’Événement narratif associé.",
    "Ce que retient le Décanteur",
    "Charge d’accueil active",
    "Charpente étanche",
    "Chemin des Vanniers",
    "Chosen transformation",
    "Cistern-sharing pact",
    "Citerne profonde de Haut-Puits",
    "Close Lower Watch’s quarters",
    "Coffret confié à Maëlys",
    "Coffret de Maëlys confié au convoi",
    "Cohort at the gates",
    "Cohort redirected to Sillon Hospice",
    "Cohorte aux portes",
    "Cohorte du Sillon",
    "Cohorte du Sillon accueillie",
    "Cohorte du Sillon refusée",
    "Cohorte redirigée vers l’Hospice du Sillon",
    "Collective registry arbitration retained",
    "Common maintenance prepared for the Council",
    "Complete trade",
    "Conclure l’échange",
    "Confier à Maëlys le relevé de l’Hospice",
    "Confiner les boues avec les équipes du convoi",
    "Consigner le frein dans le Journal causal",
    "Consigner le procédé du Décanteur itinérant",
    "Contain the sludge with convoy crews",
    "Contrepoids partagés entre les deux rives",
    "Cooperative",
    "Coopérative",
    "Copier les registres dans le Journal causal",
    "Copy the records into the causal Journal",
    "Counterweights shared between both banks",
    "Coupe du Phare éteint de Veille-Basse : la Cohorte attend devant les volumes étanches où habitants et Pèlerins préparent des couchettes.",
    "Covertly alter the revealed brake",
    "Coût connu : 2 Matériaux ; une Trace persistante pourra nourrir doute, accusation ou preuve.",
    "Coût connu : 4 Matériaux renforcent les cages communes ; aucun choix antérieur n’est annulé.",
    "Coût connu : 6 Matériaux et un accord public des Nacelliers.",
    "Coût connu : 8 L d’Eau compensent l’attente imposée aux voyageurs des deux rives.",
    "Coût connu : Ilyana restera consultée, mais sa garantie ne sera pas reconnue.",
    "Coût connu : Veille-Basse perd temporairement une technicienne de ses filtres.",
    "Coût connu : Veille-Basse reste fragile, mais la Pression d’accueil se déplace vers l’Hospice.",
    "Coût connu : chaque Colonie cédera périodiquement une équipe au Relais.",
    "Coût connu : dix-huit Habitants à abriter immédiatement ; deux équipes seulement après l’intégration.",
    "Coût connu : la Cité-caravane n’emporte qu’un relevé synthétique, mais la révélation reste acquise.",
    "Coût connu : la Cohorte restera sur les routes et ce refus reviendra aux portes de la Colonie.",
    "Coût connu : le Marché des filtres et l’ouverture des archives attendront.",
    "Coût connu : le relevé de l’Hospice sera plus lent, sans bloquer sa consolidation.",
    "Coût connu : le renseignement quitte le cercle des seuls techniciens, sans déclencher d’opération.",
    "Coût connu : les Nacelliers sauront exactement quelle infrastructure a été désignée.",
    "Coût connu : les Puits Libres porteront cette nouvelle nuisance au Conseil des Vannes.",
    "Coût connu : les familles déplacées seront écartées jusqu’au Conseil des Vannes.",
    "Coût connu : les priorités de passage devront rester publiques et contestables.",
    "Coût connu : les résidus occuperaient de la Charge et exigeraient un confinement durable.",
    "Coût connu : les équipes d’Entretien délaisseront un chantier pendant la prochaine veille.",
    "Coût connu : l’Hospice portera la Charge et demandera ensuite des places filtrées.",
    "Coût connu : l’accueil augmenterait immédiatement les besoins en Eau, Vivres et Chaleur.",
    "Coût connu : l’occasion sera consignée comme ignorée ; Veille-Basse deviendra perdue au prochain Jalon local.",
    "Coût connu : sa parole engagera personnellement l’Intendance au Conseil des Vannes.",
    "Coût connu : trente litres d’Eau du convoi soutiendront la première distribution.",
    "Coût connu : une équipe technique quitte les filtres le temps de sécuriser la copie.",
    "Create a Welcoming Load in the caravan-city",
    "Create a single 16:9 narrative event illustration for the French dieselpunk survival management game “Les Lanternes de Cendre”. Scene: two suspended industrial cable-car cages face each other above a vast cracked ash-settling basin; travellers from a deep-well settlement and refugees from a sealed lighthouse settlement visibly cooperate to redistribute heavy counterweights. A mobile lighthouse-convoy glows faintly in the distant haze. Art direction: painterly editorial concept art, muted charcoal, ash beige, oxidized copper and restrained amber light; human-scale, materially plausible machinery, weathered cables and pulleys; sober, tense, compassionate, no heroic pose. Wide composition with clear silhouettes and accessibility-friendly value contrast. No text, no letters, no logos, no UI, no watermark.",
    "Create a single 16:9 narrative event illustration matching the established “Les Lanternes de Cendre” painterly dieselpunk concept-art style. Close narrative scene: an open ancient cableway magnetic brake inside a worn industrial relay; a gloved hand hesitates above the exact mechanism while bright brass filings fall onto a dark survey cloth, leaving an unmistakable persistent trace. In the background, two cable crews wait in tense silhouette, making the ethical choice between public repair and covert alteration legible without melodrama. Muted charcoal, ash beige, oxidized copper, controlled amber task light; materially plausible machinery, strong value contrast, sober and morally tense. No text, no letters, no logos, no UI, no watermark.",
    "Create a single 16:9 narrative event illustration matching the established “Les Lanternes de Cendre” painterly dieselpunk concept-art style. Scene on a high cableway relay footbridge over ash basins: two competent women stand side by side but retain distinct roles—an older dark-haired steward named Ilyana holds an open water-sharing register, while a younger field engineer named Maëlys carries a compact weathered survey case. They face heavy cables stretching toward two different settlement banks and calmly compare proposals; cable crews work behind them. No heroic pose, no romance, no authority tableau: collaborative disagreement and practical trust. Muted charcoal, ash beige, oxidized copper, restrained amber beacon light; windblown ash, strong readable silhouettes and value contrast. No text, no legible writing, no letters, no logos, no UI, no watermark.",
    "Create a single 16:9 narrative event illustration matching the established “Les Lanternes de Cendre” painterly dieselpunk concept-art style. Scene: beneath the main drum of an old industrial cableway relay, technicians discover a precise ancient magnetic brake connected to a patterned brass plate; they mark and measure the housing without touching it. Massive pulleys and worn steel cables frame the machinery, ash dust hangs in the air, dim amber work lamps reveal the concrete target. Palette: muted charcoal, ash beige, oxidized copper, restrained amber; sober archaeological-industrial mystery, materially plausible, strong readable silhouettes and value contrast. No text, no letters, no logos, no UI, no watermark.",
    "Crews compare contained sludge with plans for a Travelling Settler and an Ark for the Displaced.",
    "Crossing disputed by both Factions",
    "Créer une Charge d’accueil dans la Cité-caravane",
    "Cutaway of Lower Watch’s dead lighthouse: the Cohort waits before sealed rooms where residents and Pilgrims prepare bunks.",
    "Câbles fatigués et contrepoids incomplets",
    "Câbles fatigués mais contrepoids coordonnés",
    "Câbles fatigués sous charge non répartie",
    "Dans le sas de Veille-Basse, deux techniciens retiennent une porte sous la cendre tandis que les Pèlerins montrent les volumes protégés encore accessibles.",
    "Dans un atelier couvert, Maëlys tend un coffret de relevés au Porte-Lanterne tandis que des équipes de charpente renforcent l’Hospice au second plan.",
    "Dated readings link the plume to the last Route Commitment; the diversion remains passable, but there is no normal return.",
    "Decision pending",
    "Decline to intervene before the next gust",
    "Deep ruts",
    "Des paniers de roseaux enduits de cendre balisent la dérive jusqu’aux ateliers suspendus.",
    "Des équipes comparent des boues confinées aux plans d’un Décanteur itinérant et d’une Arche des déplacés.",
    "Deux jeux de plans restent ouverts côte à côte ; aucun ne désigne à lui seul la forme future du convoi.",
    "Deux nacelles suspendues se font face au-dessus d’un bassin de cendre, entourées de voyageurs de Haut-Puits et de Veille-Basse qui répartissent les contrepoids.",
    "Deux voix dans le câble",
    "Dike Camp",
    "Diplomatic commitments",
    "Displaced People’s Ark",
    "Displaced People’s Ark — possibility to assess",
    "Displaced influx",
    "Distribute the counterweights between both banks",
    "Distribution valve",
    "Divert the plume towards the empty basin",
    "Dix-huit personnes du camp des Digues atteignent Veille-Basse. Épuisée mais formée à la charpente étanche, la Cohorte du Sillon demande une destination durable tandis que la Colonie fragile manque déjà de filtres.",
    "Dominant condition",
    "Décanteur itinérant",
    "Décanteur itinérant documenté",
    "Décanteur itinérant — possibilité à étudier",
    "Décision en attente",
    "Dériver le panache vers le bassin vide",
    "Eighteen people from the Dike Camp reach Lower Watch. Exhausted but trained in sealed-frame carpentry, the Sillon Cohort asks for a lasting destination while the fragile Colony is already short of filters.",
    "Elle pose le coffret entre vous, sans présenter sa propre présence comme le prix du succès.",
    "Elle pose son crayon sur le registre plutôt que sur la vanne, laissant la décision au Porte-Lanterne.",
    "En attente",
    "En mission à l’Hospice du Sillon",
    "Engagement de partage de l’eau — écho prévu au Conseil des Vannes ({moment})",
    "Engagements diplomatiques",
    "Entrust her with the sharing register",
    "Entrust the Hospice survey to Maëlys",
    "Essential revelation",
    "Exhausted",
    "Families turned away",
    "Familles écartées",
    "Fast survey in progress",
    "Fermer les volumes de Veille-Basse",
    "Filter parts",
    "Filtered spaces",
    "Filtres saturés",
    "Free Wells and Ash Pilgrims agreement",
    "Frein des Nacelles réaccordé publiquement",
    "Frein des Nacelles transformé clandestinement",
    "Frein magnétique balisé comme Cible clandestine",
    "Frein magnétique consigné comme Cible clandestine",
    "Frein magnétique des Nacelles",
    "Garantir d’abord l’autonomie de Haut-Puits",
    "Garantir le partage de l’Eau",
    "Garantir le passage vers l’Hospice du Sillon",
    "Garder Maëlys aux filtres et envoyer les charpentiers",
    "Garder le registre sous arbitrage collectif",
    "Guarantee High Well’s autonomy first",
    "Guarantee Water sharing",
    "Guarantee passage to Sillon Hospice",
    "Habitants de Veille-Basse",
    "Haut-Puits reste stable ; la relation publique se ferme.",
    "Help received",
    "Her proposal defends her belief in safe Water for everyone without granting her authority over the Council.",
    "High Well Scouts",
    "High Well autonomy guaranteed",
    "High Well deep cistern",
    "High Well remains stable; the public relationship closes.",
    "Hospice du Sillon",
    "Hospice sealed quarters opened",
    "Hospice survey completed",
    "Ilyana Voss argues for a shared crossing register; Maëlys Rive wants crews able to maintain the cables to move between Colonies. They frame two options compatible with established facts without claiming personal authority.",
    "Ilyana Voss défend un registre commun des passages ; Maëlys Rive veut que les équipes capables d’entretenir les câbles circulent entre les Colonies. Elles formulent deux options compatibles avec les faits acquis, sans réclamer d’autorité personnelle.",
    "Ilyana and Maëlys stand on a cableway footbridge, one holding a register and the other a survey case, facing cables stretched toward both banks.",
    "Ilyana asks that every opening of the cistern record its beneficiaries and cost, even though the Free Wells consider such a register intrusive.",
    "Ilyana at the last valve",
    "Ilyana demande que chaque ouverture de la citerne soit consignée avec ses bénéficiaires et son coût, même si les Puits Libres jugent ce registre intrusif.",
    "Ilyana devant la dernière vanne",
    "Ilyana et Maëlys se tiennent sur une passerelle de nacelles, l’une avec un registre et l’autre avec un coffret de relevés, face aux câbles tendus vers les deux rives.",
    "Ilyana garante du registre",
    "Ilyana guarantees the registry",
    "Ilyana holds an open register before the High Well valve while delegates await the decision.",
    "Ilyana links the shared-crossing proposal to the water commitments made at High Well.",
    "Ilyana relie la proposition de passage partagé aux engagements hydriques pris à Haut-Puits.",
    "Ilyana tient un registre ouvert devant la vanne de Haut-Puits tandis que les délégués attendent la décision.",
    "In Lower Watch’s airlock, two technicians hold a gate against the ash while Pilgrims point toward protected rooms still available.",
    "In a covered workshop, Maëlys offers the Lantern-Bearer a survey case while carpentry teams reinforce the Hospice in the background.",
    "Intervention à Veille-Basse refusée",
    "Intégration",
    "Isolated cable crews at the Relay",
    "Keep Maëlys on the filters and send the carpenters",
    "Keep the register under collective arbitration",
    "Known cost: 2 Materials; a persistent Trace may later support doubt, accusation or proof.",
    "Known cost: 4 Materials reinforce the shared cages; no earlier choice is undone.",
    "Known cost: 6 Materials and the Cable Crews’ public agreement.",
    "Known cost: 8 L of Water offset the wait imposed on travellers from both banks.",
    "Known cost: Ilyana will remain consulted, but her guarantee will not be recognized.",
    "Known cost: Lower Watch remains fragile, but the welcoming Pressure shifts to the Hospice.",
    "Known cost: Lower Watch temporarily loses one filter technician.",
    "Known cost: Maintenance crews will leave one worksite unattended during the next watch.",
    "Known cost: crossing priorities must remain public and open to challenge.",
    "Known cost: displaced families will be turned away until the Sluice Council.",
    "Known cost: each Colony will periodically assign one crew to the Relay.",
    "Known cost: her word will personally commit Stewardship at the Sluice Council.",
    "Known cost: one technical team leaves the filters while securing the copy.",
    "Known cost: residues would occupy Load and require lasting containment.",
    "Known cost: shelter eighteen inhabitants immediately; gain two teams only after integration.",
    "Known cost: sheltering people would immediately increase Water, Food and Heat needs.",
    "Known cost: the Cable Crews will know exactly which infrastructure was designated.",
    "Known cost: the Cohort remains on the roads and this refusal will return to the Colony’s gates.",
    "Known cost: the Free Wells will bring this new burden to the Sluice Council.",
    "Known cost: the Hospice carries the Load and will later ask for filtered spaces.",
    "Known cost: the Hospice survey will be slower without blocking its reinforcement.",
    "Known cost: the caravan-city carries only a summary survey, but the revelation remains known.",
    "Known cost: the filter market and archive opening must wait.",
    "Known cost: the intelligence leaves the technicians’ circle without launching an operation.",
    "Known cost: the opportunity will be recorded as ignored; Lower Watch will become lost at the next local Milestone.",
    "Known cost: thirty litres of convoy Water will support the first distribution.",
    "La Cible révélée peut être réparée au grand jour ou transformée sans consentement pour rendre les charges impossibles à discriminer. L’opération cachée toucherait une infrastructure précise et laisserait une enquête possible.",
    "La Cohorte vient du camp des Digues, compte dix-huit personnes et sait rendre habitables des volumes fissurés.",
    "La main sur le frein",
    "La négociation est tranchée.",
    "La place sous le Phare éteint",
    "La plaque de laiton porte le même motif que les courbes de reflux copiées à Veille-Basse.",
    "La porte des filtres",
    "La rive basse n’envoie ni coffret ni équipe : le refus d’intervenir à Veille-Basse revient comme une place vide dans chaque cage.",
    "Laisser les originaux sous la garde de Veille-Basse",
    "Le Réseau ancien déplaçait la cendre vers les périphéries",
    "Le boîtier, son alimentation et sa transmission sont localisés : le frein magnétique est désormais une Cible clandestine concrète, limitée à ce passage.",
    "Le capot reste ouvert devant vous ; la différence entre réparation et intervention cachée est explicite.",
    "Le coffret confié à Maëlys documente les charges de la rive basse : sa mission donne aux techniciens de Veille-Basse une voix dans la répartition.",
    "Le coffret contient des jauges anciennes et un protocole que Maëlys a reconstruit, mais aucune étape ne requiert sa présence.",
    "Le coût réellement payé pour atteindre le Relais porte déjà la marque des deux Colonies, de la Cohorte, du panache et de leurs Factions.",
    "Le frein sous la cendre",
    "Le halo du convoi a poussé une langue de cendre vers les ateliers des Vanniers. Haut-Puits demande qui portera les boues nécessaires à son confinement.",
    "Le pacte des citernes",
    "Le panache du Phare dérive vers l’est et atteint les Vanniers.",
    "Le poids des deux rives",
    "Le registre confié à Ilyana précède le convoi sur le câble : les Nacelliers traitent la garantie de partage de Haut-Puits comme une parole opposable.",
    "Le registre de jauge confirme que le partage rendrait Haut-Puits fragile sans assécher immédiatement la citerne.",
    "Le registre resté collectif arrive sans garante désignée : les Nacelliers exigent que chaque priorité de Haut-Puits soit renégociée au Relais.",
    "Leave the originals in Lower Watch’s care",
    "Les Puits Libres proposent d’ouvrir la citerne aux familles déplacées si la cité-caravane garantit des pièces de filtration jusqu’au Conseil des Vannes.",
    "Les Vanniers",
    "Les Vanniers sous le panache",
    "Les ateliers des Vanniers apparaissent sous un panache de cendre balisé par des paniers de roseaux.",
    "Les boues confinées prouvent qu’un Décanteur itinérant sécuriserait des sources contaminées, tandis que les plans de sas pourraient servir à une Arche des déplacés.",
    "Les cartes de calibration montrent que le Réseau ancien protégeait les villes productives et repoussait la cendre vers les Bassins fendus. Sa désynchronisation n’a pas créé la masse : elle a libéré ce que les périphéries recevaient déjà.",
    "Les deux Compagnes parlent depuis des rives différentes, puis nouent leurs propositions au même câble.",
    "Les deux projets réclament un châssis entier et restent incompatibles avec une transformation gratuite ou instantanée.",
    "Les marques de niveau traversent la paroi de la citerne comme les anneaux d’une dette ancienne.",
    "Les nacelles ne peuvent porter à la fois les réserves de Haut-Puits et toutes les familles venues de Veille-Basse. Les Puits Libres et les Pèlerins réclament chacun la priorité promise en amont.",
    "Les registres du reflux",
    "Les registres d’approche restent ouverts côte à côte : aucun délégué ne peut effacer la rive opposée.",
    "Les relevés datés relient le panache au dernier Engagement de route ; le détour reste praticable, mais sans retour normal.",
    "Les techniciens confirment deux réponses viables avant la prochaine rafale ; aucune perte n’est encore irréversible.",
    "Les tracés, dates de maintenance et volumes déplacés se recoupent ; cette révélation ne dépend du témoignage d’aucun Compagnon.",
    "Les verrous vibrent ; entre les deux rafales demeure une fenêtre assez longue pour agir.",
    "Les équipes gardées à Veille-Basse ne peuvent renforcer les câbles : leur absence rend visible le prix de la priorité donnée à la Colonie.",
    "Level marks cross the cistern wall like the rings of an old debt.",
    "Local pressures",
    "Loss announced — intervention opportunity",
    "Lower Watch airlock reinforced",
    "Lower Watch and Sillon Hospice",
    "Lower Watch intervention refused",
    "Lower Watch residents",
    "Lower Watch technical archives",
    "Lower Watch technicians",
    "Lower Watch workshop",
    "Lower Watch — filter gate",
    "Lower Watch — sealed quarters",
    "Lui confier le registre de partage",
    "L’accueil occupera les équipes pendant dix minutes avant que deux équipes de charpente puissent rejoindre le convoi.",
    "Machinerie sous le Relais",
    "Machinery beneath the Relay",
    "Magnetic brake marked as a Covert Target",
    "Magnetic brake recorded as a Covert Target",
    "Maintenance commune préparée pour le Conseil",
    "Mandat des Nacelliers non reconnu",
    "Marché de besoins",
    "Marché de l’eau",
    "Mark the housing and its telltales",
    "Maëlys Rive",
    "Maëlys Rive, a technician of the dead lighthouse, offers her survey case to inspect the Hospice conduits. Her knowledge opens a more precise route; the carpentry teams can also succeed without her.",
    "Maëlys Rive, technicienne du Phare éteint, propose son coffret de relevés pour reconnaître les conduites de l’Hospice. Son savoir ouvre une voie plus précise ; les équipes de charpente peuvent aussi réussir sans elle.",
    "Maëlys and the sealed case",
    "Maëlys et le coffret étanche",
    "Maëlys links common maintenance to the Cohort’s fate and Lower Watch’s technicians.",
    "Maëlys relie la maintenance commune au devenir de la Cohorte et aux techniciens de Veille-Basse.",
    "Maëlys’s survey case entrusted to the convoy",
    "Maëlys’s teams kept at Lower Watch",
    "Nacelliers des Vannes",
    "Nacelliers isolés du Relais",
    "Nacelliers mandatés par les deux branches",
    "Needs market",
    "Negotiation open",
    "No decision",
    "No diplomatic commitment.",
    "No established control",
    "No external input image; generated from the written Ilyana Voss and Maëlys Rive companion-story brief.",
    "No external input image; generated from the written Maëlys Rive event brief.",
    "No external input image; generated from the written Nacelles mystery brief.",
    "No external input image; generated from the written Nacelles regional-conflict brief.",
    "No external input image; generated from the written Nacelles systemic-consequence brief.",
    "No external input image; generated from the written Veille-Basse event brief.",
    "No external input image; generated from the written Veille-Basse mystery-revelation brief.",
    "No transformation imposed.",
    "Négociation de l’eau",
    "Négociation ouverte",
    "Offer exhausted",
    "Offre épuisée",
    "On mission at Sillon Hospice",
    "Open the Hospice’s filtered chambers",
    "Opening the housing scatters identifiable brass filings; they will survive the regional transition as a Covert Trace.",
    "Ornières profondes",
    "Ouvrir les volumes filtrés de l’Hospice",
    "Pacte de partage des citernes",
    "Panache dérivé vers le bassin vide",
    "Partage organisé",
    "Partager l’eau",
    "Passage contesté par les deux Factions",
    "Passage des Nacelles réservé",
    "Passage partagé préparé pour le Conseil",
    "Passerelle du Relais",
    "Persistent brass-filings Trace",
    "Perte annoncée — occasion d’intervention",
    "Pièces de filtration",
    "Places filtrées",
    "Plume diverted to the empty basin",
    "Plume sludge contained",
    "Porter la maintenance commune au Conseil des Vannes",
    "Porter le passage partagé au Conseil des Vannes",
    "Possible transformations",
    "Pressions locales",
    "Pressures",
    "Prosperous",
    "Prospère",
    "Protect the reserves",
    "Protéger les réserves",
    "Public relationship",
    "Record the Travelling Settler process",
    "Record the brake in the causal Journal",
    "Records entrusted to Lower Watch",
    "Redirected",
    "Redirigée",
    "Registres confiés à Veille-Basse",
    "Registres du reflux copiés",
    "Reinforced",
    "Relais des Nacelles",
    "Relais des Vannes",
    "Relation publique",
    "Relay footbridge",
    "Relevé de l’Hospice terminé",
    "Relevé lent en cours",
    "Relevé non planifié",
    "Relevé rapide en cours",
    "Relevé transmis par la branche d’approche",
    "Remedies for the well crews",
    "Remèdes pour les puisatiers",
    "Renforcé",
    "Renoncer à intervenir avant la prochaine rafale",
    "Reserve the next cage for the convoy",
    "Reserves depleted",
    "Reserves protected",
    "Retune the brake publicly",
    "Roads beyond Lower Watch",
    "Room beneath the dead lighthouse",
    "Routes hors de Veille-Basse",
    "Routes, maintenance dates, and displaced volumes agree; this revelation depends on no Companion’s testimony.",
    "Réaccorder publiquement le frein",
    "Répartir les contrepoids entre les deux rives",
    "Réserver la prochaine cage au convoi",
    "Réserves entamées",
    "Réserves protégées",
    "Révélation essentielle",
    "Sa proposition défend sa conviction d’une Eau sûre pour tous sans lui donner autorité sur le Conseil.",
    "Salle d’archives sans texte lisible : cartes gravées, conduites et tambours de calibration montrent la cendre déplacée des phares centraux vers les Bassins périphériques.",
    "Sans contrôle établi",
    "Sas de Veille-Basse renforcé",
    "Saturated filters",
    "Sealed-frame carpentry",
    "Secondary inhabited site",
    "Share the water",
    "Shared crossing prepared for the Council",
    "Sharing organized",
    "She places her pencil on the register rather than the valve, leaving the decision to the Lantern-Bearer.",
    "She sets the case between you without presenting her own presence as the price of success.",
    "Sillon Cohort",
    "Sillon Cohort refused",
    "Sillon Cohort welcomed",
    "Sillon Hospice",
    "Site habité secondaire",
    "Slow survey in progress",
    "Sluice Cable Crews",
    "Sluice Relay",
    "Sous Charge d’accueil",
    "Sous la tour éteinte, chaque couchette libre a déjà un nom ; le choix porte sur la communauté qui assumera les nouveaux arrivants.",
    "Sous le tambour d’une nacelle, des techniciens découvrent un frein magnétique ancien relié à une plaque de laiton et le balisent sans le toucher.",
    "Sous le tambour principal, un frein magnétique du Réseau ancien module encore chaque charge. Ses impulsions concordent avec les registres montrant le déplacement historique de la cendre vers les périphéries.",
    "Specialty",
    "Spécialité",
    "Sur la table, les anciennes courbes convergent toutes vers les mêmes territoires sacrifiés.",
    "Survey case entrusted to Maëlys",
    "Survey not planned",
    "Survey relayed by the approach branch",
    "Teams sent without Maëlys",
    "Techniciens de Veille-Basse",
    "The Ancient Network displaced ash toward the peripheries",
    "The Basketmakers",
    "The Basketmakers under the plume",
    "The Basketmakers’ workshops sit beneath an ash plume marked by reed baskets.",
    "The Cohort comes from the Dike Camp, numbers eighteen people, and knows how to make cracked chambers habitable.",
    "The Free Wells will open the cistern to displaced families if the caravan-city guarantees filtration parts until the Sluice Council.",
    "The Lighthouse plume drifts east and reaches the Basketmakers.",
    "The backflow records",
    "The brake beneath the ash",
    "The brass plate bears the same pattern as the reflux curves copied at Lower Watch.",
    "The cableways cannot carry both High Well’s reserves and every family arriving from Lower Watch. The Free Wells and Ash Pilgrims each demand the priority promised upstream.",
    "The case entrusted to Maëlys documents loads from the lower bank: her mission gives Lower Watch technicians a voice in the allocation.",
    "The case holds ancient gauges and a protocol Maëlys reconstructed, but no step requires her presence.",
    "The cistern pact",
    "The collective register arrives without a named guarantor: the cable crews require every High Well priority to be renegotiated at the Relay.",
    "The contained sludge proves that a Travelling Settler could secure contaminated sources, while the airlock plans could serve an Ark for the Displaced.",
    "The convoy’s watch halo pushed an ash tongue towards the Basketmakers’ workshops. High Well asks who will carry the sludge needed to contain it.",
    "The cost already paid to reach the Relay bears the mark of both Colonies, the Cohort, the plume and their Factions.",
    "The filter gate",
    "The gauge register confirms that sharing would leave High Well fragile without immediately draining the cistern.",
    "The housing remains open before you; the difference between repair and hidden intervention is explicit.",
    "The housing, power feed and transmission are located: the magnetic brake is now a concrete Covert Target limited to this crossing.",
    "The locks shake; between two gusts, a window long enough to act remains.",
    "The lower bank sends neither case nor crew: refusing to intervene at Lower Watch returns as an empty place in every cage.",
    "The negotiation is settled.",
    "The register entrusted to Ilyana reaches the cable crews first: they treat High Well’s sharing guarantee as a commitment that can be challenged.",
    "The revealed Target can be repaired openly or altered without consent so loads can no longer be discriminated. The hidden operation would affect a precise infrastructure and leave room for an investigation.",
    "The teams kept at Lower Watch cannot reinforce the cables: their absence exposes the cost of prioritizing the Colony.",
    "The technicians confirm two viable responses before the next gust; no loss is irreversible yet.",
    "The two Companions speak from different banks, then knot their proposals to the same cable.",
    "The weight of both banks",
    "This choice is settled in the associated narrative Event.",
    "Toute ouverture du boîtier disperse une limaille de laiton identifiable ; elle survivra au changement de Région comme Trace clandestine.",
    "Trace de limaille de laiton persistante",
    "Trade a mobile Lighthouse survey for sealed filters",
    "Trade framing Materials for technician support",
    "Trades remaining",
    "Transactional",
    "Transactionnelle",
    "Transformation choisie",
    "Transformations possibles",
    "Transformer clandestinement le frein révélé",
    "Travelling Settler",
    "Travelling Settler documented",
    "Travelling Settler — possibility to assess",
    "Two sets of plans remain open side by side; neither alone determines the convoy’s future shape.",
    "Two suspended cable cages face one another above an ash basin while travellers from High Well and Lower Watch distribute counterweights.",
    "Two voices in the cable",
    "Under Welcoming Load",
    "Une main gantée hésite au-dessus du frein magnétique ouvert tandis que de la limaille de laiton brillante tombe sur un tissu de relevé.",
    "Une rafale force le sas extérieur. Veille-Basse est avertie : sans intervention, ses deux équipes ne pourront pas maintenir simultanément les filtres, les archives et l’accueil.",
    "Use case: wide 16:9 story-event illustration for the premium narrative game “Lanternes de cendre”. Create one production-ready character-and-environment image. The attached Cité-Caravane image is a style and world reference only: match its elevated oblique industrial setting, painterly-realistic detail, charcoal/ash blue-black palette, restrained warm amber lantern light, and desolate ash-storm atmosphere. New scene: Ilyana Voss, a practical adult convoy companion in ash-dark work clothes, stands at High Well’s large water distribution valve, one hand near the brass control wheel. Beside her lies an open blank registry with visible ruled pages but absolutely no readable writing. Across the valve table, several local delegates and convoy witnesses face her, making the tension between entrusting her as guarantor and retaining collective arbitration visually clear. Include cistern pipes and the well infrastructure behind them. Respectful non-glamourized character depiction, cinematic wide composition, high environmental storytelling, no readable text, no typography, no logos, no watermark, no weapons, no UI. Do not copy the exact composition of the reference.",
    "Use case: wide 16:9 story-event illustration for the premium narrative game “Lanternes de cendre”. Create one production-ready environment image. The attached Cité-Caravane image is a style and world reference only: match its elevated oblique viewpoint, intricate industrial machinery, painterly-realistic detail, charcoal/ash blue-black palette, restrained warm amber lantern light, and desolate ash-storm atmosphere. New scene: a sludge confinement yard beside High Well. Thick dark settling sludge is held behind patched metal baffles and portable pipes. In the foreground, an engineering table clearly displays two distinct sets of visual plans without readable writing: one for a compact travelling settler mounted on a caravan chassis, the other for a broad ark-like shelter for displaced families. Mechanics compare the two options, but neither machine is being built yet. Make the two possible transformations visually distinct and the unresolved choice unmistakable. Cinematic wide composition, high environmental storytelling, no readable text, no typography, no logos, no watermark, no weapons, no UI. Do not copy the exact composition of the reference.",
    "Use case: wide 16:9 story-event illustration for the premium narrative game “Lanternes de cendre”. Create one production-ready environment image. The attached Cité-Caravane image is a style and world reference only: match its elevated oblique viewpoint, intricate industrial machinery, painterly-realistic detail, charcoal/ash blue-black palette, restrained warm amber lantern light, and desolate ash-storm atmosphere. New scene: the Basketmakers’ district below High Well, with reed-weaving workshops, drying reed bundles, woven baskets and filter mats, narrow water channels, and a dense ash plume visibly drifting down onto the district from distant settling basins. A few small anonymous workers protect their workshops; the threatened craft community and cause-and-effect of the plume must be visually clear. Cinematic wide composition, high environmental storytelling, no readable text, no typography, no logos, no watermark, no weapons, no UI. Do not copy the exact composition of the reference.",
    "Vanne de répartition",
    "Veille-Basse et l’Hospice du Sillon",
    "Veille-Basse — porte des filtres",
    "Veille-Basse — volumes étanches",
    "Volumes de l’Hospice ouverts",
    "Water Market",
    "Water autonomy threatened",
    "Water negotiation",
    "Water-sharing pledge — to be echoed at the Sluice Council ({moment})",
    "Welcoming Load active",
    "Welcoming them will occupy the teams for ten minutes before two carpentry teams can join the convoy.",
    "What the Settler retains",
    "Wide 16:9 painterly industrial 2D archive vault in Veille-Basse’s dead lighthouse, where physical maps, airflow channels and calibration drums reveal that the ancient network displaced toxic ash from protected cities toward peripheral basins; understandable without a Companion, no readable text, label, UI, logo or watermark.",
    "Wide 16:9 painterly industrial 2D scene of Veille-Basse’s failing sealed gate during an ash gust, with two technician teams bracing filters and Ash Pilgrims asking to open protected space; an explicit warning with a visible possible intervention, no text, label, UI, logo or watermark.",
    "Wide 16:9 painterly industrial 2D scene of the sealed lower chambers of an extinguished lighthouse at Veille-Basse as an exhausted refugee cohort reaches the crowded inhabited entrance; cold slate exterior, warm amber refuge, readable ensemble, no text, label, UI, logo or watermark.",
    "Wide 16:9 painterly industrial 2D workshop passage where Maëlys Rive offers a sealed survey case while refugee carpentry teams prepare the Hospice du Sillon; grounded ensemble rather than heroic portrait, no text, label, UI, logo or watermark.",
    "Worn cables and incomplete counterweights",
    "Worn cables under an unbalanced load",
    "Worn cables with coordinated counterweights",
    "airlock reinforcement",
    "archive review",
    "filter maintenance",
    "haut-puits-decanteur.webp",
    "haut-puits-ilyana.webp",
    "haut-puits-vanniers.webp",
    "lecture des archives",
    "maintien des filtres",
    "nacelles-compagnes.webp",
    "nacelles-deux-rives.webp",
    "nacelles-frein.webp",
    "nacelles-trace.webp",
    "renfort des sas",
    "veille-basse-archives.webp",
    "veille-basse-cohorte.webp",
    "veille-basse-maelys.webp",
    "veille-basse-porte.webp",
    "À Veille-Basse",
    "Échanger des Matériaux de charpente contre le renfort des techniciens",
    "Échanger un relevé du Phare mobile contre des filtres étanches",
    "Échanges restants",
    "Éclaireurs de Haut-Puits",
    "Équipes de Maëlys maintenues à Veille-Basse",
    "Équipes envoyées sans Maëlys",
    "État dominant",
    "−30 L d’eau ; relation coopérative ; engagement au Conseil des Vannes.",
    "−30 L water; cooperative relationship; Sluice Council pledge."
  ],
  "nomsDAssets": [
    "haut-puits-decanteur.webp",
    "haut-puits-ilyana.webp",
    "haut-puits-vanniers.webp",
    "nacelles-compagnes.webp",
    "nacelles-deux-rives.webp",
    "nacelles-frein.webp",
    "nacelles-trace.webp",
    "veille-basse-archives.webp",
    "veille-basse-cohorte.webp",
    "veille-basse-maelys.webp",
    "veille-basse-porte.webp"
  ]
} as const;
