// Ce fichier est généré par npm run content:compile.
export default {
  "version": 1,
  "fragments": [
    "/api/commercial/assets/haut-puits-decanteur.webp",
    "/api/commercial/assets/haut-puits-ilyana.webp",
    "/api/commercial/assets/haut-puits-vanniers.webp",
    "/api/commercial/assets/veille-basse-archives.webp",
    "/api/commercial/assets/veille-basse-cohorte.webp",
    "/api/commercial/assets/veille-basse-maelys.webp",
    "/api/commercial/assets/veille-basse-porte.webp",
    "2 teams integrated",
    "2 équipes intégrées",
    "Across the table, every old curve converges on the same sacrificed territories.",
    "Adapt the airlocks for the Ark for the Displaced",
    "Adapter les sas pour l’Arche des déplacés",
    "Affecter les techniciens au renfort du sas",
    "Afflux de déplacés",
    "Aide reçue",
    "An ash gust strains the outer airlock. Lower Watch is warned: without intervention, its two teams cannot maintain the filters, archives, and welcome at the same time.",
    "Arbitrage collectif du registre maintenu",
    "Arche des déplacés",
    "Arche des déplacés documentée",
    "Arche des déplacés — possibilité à étudier",
    "Archive room without readable text: engraved maps, conduits, and calibration drums show ash displaced from central lighthouses toward peripheral Basins.",
    "Archives opened — ash displacement documented",
    "Archives ouvertes — déplacement des cendres documenté",
    "Archives scellées",
    "Archives sealed",
    "Archives techniques de Veille-Basse",
    "Ark for the Displaced documented",
    "Around the deep cistern valve, Free Wells delegates and displaced families await the Lantern-Bearer’s decision.",
    "Ash-coated reed baskets mark the drift all the way to the suspended workshops.",
    "Assign the technicians to reinforce the airlock",
    "At Lower Watch",
    "Atelier de Veille-Basse",
    "Aucun engagement diplomatique.",
    "Aucune décision",
    "Aucune transformation imposée.",
    "Autonomie de Haut-Puits garantie",
    "Autonomie hydrique menacée",
    "Autour de la vanne de la citerne profonde, les délégués des Puits Libres et les familles déplacées attendent la décision du Porte-Lanterne.",
    "Backflow records copied",
    "Basketmakers’ Path",
    "Beneath the dead tower, every free bunk already has a name; the choice is which community will carry the newcomers.",
    "Both projects require an entire chassis and remain incompatible with a free or instant transformation.",
    "Boues du panache confinées",
    "Calibration maps show that the Ancient Network protected productive cities and pushed ash toward the Fractured Basins. Its loss of synchronization did not create the mass: it released what the peripheries had always received.",
    "Camp des Digues",
    "Caravan-city",
    "Ce choix se tranche dans l’Événement narratif associé.",
    "Ce que retient le Décanteur",
    "Charge d’accueil active",
    "Charpente étanche",
    "Chemin des Vanniers",
    "Chosen transformation",
    "Cistern-sharing pact",
    "Citerne profonde de Haut-Puits",
    "Close Lower Watch’s quarters",
    "Coffret confié à Maëlys",
    "Coffret de Maëlys confié au convoi",
    "Cohort at the gates",
    "Cohort redirected to Sillon Hospice",
    "Cohorte aux portes",
    "Cohorte du Sillon",
    "Cohorte du Sillon accueillie",
    "Cohorte du Sillon refusée",
    "Cohorte redirigée vers l’Hospice du Sillon",
    "Collective registry arbitration retained",
    "Complete trade",
    "Conclure l’échange",
    "Confier à Maëlys le relevé de l’Hospice",
    "Confiner les boues avec les équipes du convoi",
    "Consigner le procédé du Décanteur itinérant",
    "Contain the sludge with convoy crews",
    "Cooperative",
    "Coopérative",
    "Copier les registres dans le Journal causal",
    "Copy the records into the causal Journal",
    "Coupe du Phare éteint de Veille-Basse : la Cohorte attend devant les volumes étanches où habitants et Pèlerins préparent des couchettes.",
    "Coût connu : Ilyana restera consultée, mais sa garantie ne sera pas reconnue.",
    "Coût connu : Veille-Basse perd temporairement une technicienne de ses filtres.",
    "Coût connu : Veille-Basse reste fragile, mais la Pression d’accueil se déplace vers l’Hospice.",
    "Coût connu : dix-huit Habitants à abriter immédiatement ; deux équipes seulement après l’intégration.",
    "Coût connu : la Cité-caravane n’emporte qu’un relevé synthétique, mais la révélation reste acquise.",
    "Coût connu : la Cohorte restera sur les routes et ce refus reviendra aux portes de la Colonie.",
    "Coût connu : le Marché des filtres et l’ouverture des archives attendront.",
    "Coût connu : le relevé de l’Hospice sera plus lent, sans bloquer sa consolidation.",
    "Coût connu : les Puits Libres porteront cette nouvelle nuisance au Conseil des Vannes.",
    "Coût connu : les familles déplacées seront écartées jusqu’au Conseil des Vannes.",
    "Coût connu : les résidus occuperaient de la Charge et exigeraient un confinement durable.",
    "Coût connu : les équipes d’Entretien délaisseront un chantier pendant la prochaine veille.",
    "Coût connu : l’Hospice portera la Charge et demandera ensuite des places filtrées.",
    "Coût connu : l’accueil augmenterait immédiatement les besoins en Eau, Vivres et Chaleur.",
    "Coût connu : l’occasion sera consignée comme ignorée ; Veille-Basse deviendra perdue au prochain Jalon local.",
    "Coût connu : sa parole engagera personnellement l’Intendance au Conseil des Vannes.",
    "Coût connu : trente litres d’Eau du convoi soutiendront la première distribution.",
    "Coût connu : une équipe technique quitte les filtres le temps de sécuriser la copie.",
    "Create a Welcoming Load in the caravan-city",
    "Crews compare contained sludge with plans for a Travelling Settler and an Ark for the Displaced.",
    "Créer une Charge d’accueil dans la Cité-caravane",
    "Cutaway of Lower Watch’s dead lighthouse: the Cohort waits before sealed rooms where residents and Pilgrims prepare bunks.",
    "Dans le sas de Veille-Basse, deux techniciens retiennent une porte sous la cendre tandis que les Pèlerins montrent les volumes protégés encore accessibles.",
    "Dans un atelier couvert, Maëlys tend un coffret de relevés au Porte-Lanterne tandis que des équipes de charpente renforcent l’Hospice au second plan.",
    "Dated readings link the plume to the last Route Commitment; the diversion remains passable, but there is no normal return.",
    "Decision pending",
    "Decline to intervene before the next gust",
    "Deep ruts",
    "Des paniers de roseaux enduits de cendre balisent la dérive jusqu’aux ateliers suspendus.",
    "Des équipes comparent des boues confinées aux plans d’un Décanteur itinérant et d’une Arche des déplacés.",
    "Deux jeux de plans restent ouverts côte à côte ; aucun ne désigne à lui seul la forme future du convoi.",
    "Dike Camp",
    "Diplomatic commitments",
    "Displaced People’s Ark",
    "Displaced People’s Ark — possibility to assess",
    "Displaced influx",
    "Distribution valve",
    "Divert the plume towards the empty basin",
    "Dix-huit personnes du camp des Digues atteignent Veille-Basse. Épuisée mais formée à la charpente étanche, la Cohorte du Sillon demande une destination durable tandis que la Colonie fragile manque déjà de filtres.",
    "Dominant condition",
    "Décanteur itinérant",
    "Décanteur itinérant documenté",
    "Décanteur itinérant — possibilité à étudier",
    "Décision en attente",
    "Dériver le panache vers le bassin vide",
    "Eighteen people from the Dike Camp reach Lower Watch. Exhausted but trained in sealed-frame carpentry, the Sillon Cohort asks for a lasting destination while the fragile Colony is already short of filters.",
    "Elle pose le coffret entre vous, sans présenter sa propre présence comme le prix du succès.",
    "Elle pose son crayon sur le registre plutôt que sur la vanne, laissant la décision au Porte-Lanterne.",
    "En attente",
    "En mission à l’Hospice du Sillon",
    "Engagement de partage de l’eau — écho prévu au Conseil des Vannes ({moment})",
    "Engagements diplomatiques",
    "Entrust her with the sharing register",
    "Entrust the Hospice survey to Maëlys",
    "Essential revelation",
    "Exhausted",
    "Families turned away",
    "Familles écartées",
    "Fast survey in progress",
    "Fermer les volumes de Veille-Basse",
    "Filter parts",
    "Filtered spaces",
    "Filtres saturés",
    "Garantir d’abord l’autonomie de Haut-Puits",
    "Garantir le partage de l’Eau",
    "Garantir le passage vers l’Hospice du Sillon",
    "Garder Maëlys aux filtres et envoyer les charpentiers",
    "Garder le registre sous arbitrage collectif",
    "Guarantee High Well’s autonomy first",
    "Guarantee Water sharing",
    "Guarantee passage to Sillon Hospice",
    "Habitants de Veille-Basse",
    "Haut-Puits reste stable ; la relation publique se ferme.",
    "Help received",
    "Her proposal defends her belief in safe Water for everyone without granting her authority over the Council.",
    "High Well Scouts",
    "High Well autonomy guaranteed",
    "High Well deep cistern",
    "High Well remains stable; the public relationship closes.",
    "Hospice du Sillon",
    "Hospice sealed quarters opened",
    "Hospice survey completed",
    "Ilyana asks that every opening of the cistern record its beneficiaries and cost, even though the Free Wells consider such a register intrusive.",
    "Ilyana at the last valve",
    "Ilyana demande que chaque ouverture de la citerne soit consignée avec ses bénéficiaires et son coût, même si les Puits Libres jugent ce registre intrusif.",
    "Ilyana devant la dernière vanne",
    "Ilyana garante du registre",
    "Ilyana guarantees the registry",
    "Ilyana holds an open register before the High Well valve while delegates await the decision.",
    "Ilyana tient un registre ouvert devant la vanne de Haut-Puits tandis que les délégués attendent la décision.",
    "In Lower Watch’s airlock, two technicians hold a gate against the ash while Pilgrims point toward protected rooms still available.",
    "In a covered workshop, Maëlys offers the Lantern-Bearer a survey case while carpentry teams reinforce the Hospice in the background.",
    "Intervention à Veille-Basse refusée",
    "Intégration",
    "Keep Maëlys on the filters and send the carpenters",
    "Keep the register under collective arbitration",
    "Known cost: Ilyana will remain consulted, but her guarantee will not be recognized.",
    "Known cost: Lower Watch remains fragile, but the welcoming Pressure shifts to the Hospice.",
    "Known cost: Lower Watch temporarily loses one filter technician.",
    "Known cost: Maintenance crews will leave one worksite unattended during the next watch.",
    "Known cost: displaced families will be turned away until the Sluice Council.",
    "Known cost: her word will personally commit Stewardship at the Sluice Council.",
    "Known cost: one technical team leaves the filters while securing the copy.",
    "Known cost: residues would occupy Load and require lasting containment.",
    "Known cost: shelter eighteen inhabitants immediately; gain two teams only after integration.",
    "Known cost: sheltering people would immediately increase Water, Food and Heat needs.",
    "Known cost: the Cohort remains on the roads and this refusal will return to the Colony’s gates.",
    "Known cost: the Free Wells will bring this new burden to the Sluice Council.",
    "Known cost: the Hospice carries the Load and will later ask for filtered spaces.",
    "Known cost: the Hospice survey will be slower without blocking its reinforcement.",
    "Known cost: the caravan-city carries only a summary survey, but the revelation remains known.",
    "Known cost: the filter market and archive opening must wait.",
    "Known cost: the opportunity will be recorded as ignored; Lower Watch will become lost at the next local Milestone.",
    "Known cost: thirty litres of convoy Water will support the first distribution.",
    "La Cohorte vient du camp des Digues, compte dix-huit personnes et sait rendre habitables des volumes fissurés.",
    "La négociation est tranchée.",
    "La place sous le Phare éteint",
    "La porte des filtres",
    "Laisser les originaux sous la garde de Veille-Basse",
    "Le Réseau ancien déplaçait la cendre vers les périphéries",
    "Le coffret contient des jauges anciennes et un protocole que Maëlys a reconstruit, mais aucune étape ne requiert sa présence.",
    "Le halo du convoi a poussé une langue de cendre vers les ateliers des Vanniers. Haut-Puits demande qui portera les boues nécessaires à son confinement.",
    "Le pacte des citernes",
    "Le panache du Phare dérive vers l’est et atteint les Vanniers.",
    "Le registre de jauge confirme que le partage rendrait Haut-Puits fragile sans assécher immédiatement la citerne.",
    "Leave the originals in Lower Watch’s care",
    "Les Puits Libres proposent d’ouvrir la citerne aux familles déplacées si la cité-caravane garantit des pièces de filtration jusqu’au Conseil des Vannes.",
    "Les Vanniers",
    "Les Vanniers sous le panache",
    "Les ateliers des Vanniers apparaissent sous un panache de cendre balisé par des paniers de roseaux.",
    "Les boues confinées prouvent qu’un Décanteur itinérant sécuriserait des sources contaminées, tandis que les plans de sas pourraient servir à une Arche des déplacés.",
    "Les cartes de calibration montrent que le Réseau ancien protégeait les villes productives et repoussait la cendre vers les Bassins fendus. Sa désynchronisation n’a pas créé la masse : elle a libéré ce que les périphéries recevaient déjà.",
    "Les deux projets réclament un châssis entier et restent incompatibles avec une transformation gratuite ou instantanée.",
    "Les marques de niveau traversent la paroi de la citerne comme les anneaux d’une dette ancienne.",
    "Les registres du reflux",
    "Les relevés datés relient le panache au dernier Engagement de route ; le détour reste praticable, mais sans retour normal.",
    "Les techniciens confirment deux réponses viables avant la prochaine rafale ; aucune perte n’est encore irréversible.",
    "Les tracés, dates de maintenance et volumes déplacés se recoupent ; cette révélation ne dépend du témoignage d’aucun Compagnon.",
    "Les verrous vibrent ; entre les deux rafales demeure une fenêtre assez longue pour agir.",
    "Level marks cross the cistern wall like the rings of an old debt.",
    "Local pressures",
    "Loss announced — intervention opportunity",
    "Lower Watch airlock reinforced",
    "Lower Watch and Sillon Hospice",
    "Lower Watch intervention refused",
    "Lower Watch residents",
    "Lower Watch technical archives",
    "Lower Watch technicians",
    "Lower Watch workshop",
    "Lower Watch — filter gate",
    "Lower Watch — sealed quarters",
    "Lui confier le registre de partage",
    "L’accueil occupera les équipes pendant dix minutes avant que deux équipes de charpente puissent rejoindre le convoi.",
    "Marché de besoins",
    "Marché de l’eau",
    "Maëlys Rive",
    "Maëlys Rive, a technician of the dead lighthouse, offers her survey case to inspect the Hospice conduits. Her knowledge opens a more precise route; the carpentry teams can also succeed without her.",
    "Maëlys Rive, technicienne du Phare éteint, propose son coffret de relevés pour reconnaître les conduites de l’Hospice. Son savoir ouvre une voie plus précise ; les équipes de charpente peuvent aussi réussir sans elle.",
    "Maëlys and the sealed case",
    "Maëlys et le coffret étanche",
    "Maëlys’s survey case entrusted to the convoy",
    "Maëlys’s teams kept at Lower Watch",
    "Needs market",
    "Negotiation open",
    "No decision",
    "No diplomatic commitment.",
    "No established control",
    "No external input image; generated from the written Maëlys Rive event brief.",
    "No external input image; generated from the written Veille-Basse event brief.",
    "No external input image; generated from the written Veille-Basse mystery-revelation brief.",
    "No transformation imposed.",
    "Négociation de l’eau",
    "Négociation ouverte",
    "Offer exhausted",
    "Offre épuisée",
    "On mission at Sillon Hospice",
    "Open the Hospice’s filtered chambers",
    "Ornières profondes",
    "Ouvrir les volumes filtrés de l’Hospice",
    "Pacte de partage des citernes",
    "Panache dérivé vers le bassin vide",
    "Partage organisé",
    "Partager l’eau",
    "Perte annoncée — occasion d’intervention",
    "Pièces de filtration",
    "Places filtrées",
    "Plume diverted to the empty basin",
    "Plume sludge contained",
    "Possible transformations",
    "Pressions locales",
    "Pressures",
    "Prosperous",
    "Prospère",
    "Protect the reserves",
    "Protéger les réserves",
    "Public relationship",
    "Record the Travelling Settler process",
    "Records entrusted to Lower Watch",
    "Redirected",
    "Redirigée",
    "Registres confiés à Veille-Basse",
    "Registres du reflux copiés",
    "Reinforced",
    "Relais des Vannes",
    "Relation publique",
    "Relevé de l’Hospice terminé",
    "Relevé lent en cours",
    "Relevé non planifié",
    "Relevé rapide en cours",
    "Remedies for the well crews",
    "Remèdes pour les puisatiers",
    "Renforcé",
    "Renoncer à intervenir avant la prochaine rafale",
    "Reserves depleted",
    "Reserves protected",
    "Roads beyond Lower Watch",
    "Room beneath the dead lighthouse",
    "Routes hors de Veille-Basse",
    "Routes, maintenance dates, and displaced volumes agree; this revelation depends on no Companion’s testimony.",
    "Réserves entamées",
    "Réserves protégées",
    "Révélation essentielle",
    "Sa proposition défend sa conviction d’une Eau sûre pour tous sans lui donner autorité sur le Conseil.",
    "Salle d’archives sans texte lisible : cartes gravées, conduites et tambours de calibration montrent la cendre déplacée des phares centraux vers les Bassins périphériques.",
    "Sans contrôle établi",
    "Sas de Veille-Basse renforcé",
    "Saturated filters",
    "Sealed-frame carpentry",
    "Secondary inhabited site",
    "Share the water",
    "Sharing organized",
    "She places her pencil on the register rather than the valve, leaving the decision to the Lantern-Bearer.",
    "She sets the case between you without presenting her own presence as the price of success.",
    "Sillon Cohort",
    "Sillon Cohort refused",
    "Sillon Cohort welcomed",
    "Sillon Hospice",
    "Site habité secondaire",
    "Slow survey in progress",
    "Sluice Relay",
    "Sous Charge d’accueil",
    "Sous la tour éteinte, chaque couchette libre a déjà un nom ; le choix porte sur la communauté qui assumera les nouveaux arrivants.",
    "Specialty",
    "Spécialité",
    "Sur la table, les anciennes courbes convergent toutes vers les mêmes territoires sacrifiés.",
    "Survey case entrusted to Maëlys",
    "Survey not planned",
    "Teams sent without Maëlys",
    "Techniciens de Veille-Basse",
    "The Ancient Network displaced ash toward the peripheries",
    "The Basketmakers",
    "The Basketmakers under the plume",
    "The Basketmakers’ workshops sit beneath an ash plume marked by reed baskets.",
    "The Cohort comes from the Dike Camp, numbers eighteen people, and knows how to make cracked chambers habitable.",
    "The Free Wells will open the cistern to displaced families if the caravan-city guarantees filtration parts until the Sluice Council.",
    "The Lighthouse plume drifts east and reaches the Basketmakers.",
    "The backflow records",
    "The case holds ancient gauges and a protocol Maëlys reconstructed, but no step requires her presence.",
    "The cistern pact",
    "The contained sludge proves that a Travelling Settler could secure contaminated sources, while the airlock plans could serve an Ark for the Displaced.",
    "The convoy’s watch halo pushed an ash tongue towards the Basketmakers’ workshops. High Well asks who will carry the sludge needed to contain it.",
    "The filter gate",
    "The gauge register confirms that sharing would leave High Well fragile without immediately draining the cistern.",
    "The locks shake; between two gusts, a window long enough to act remains.",
    "The negotiation is settled.",
    "The technicians confirm two viable responses before the next gust; no loss is irreversible yet.",
    "This choice is settled in the associated narrative Event.",
    "Trade a mobile Lighthouse survey for sealed filters",
    "Trade framing Materials for technician support",
    "Trades remaining",
    "Transactional",
    "Transactionnelle",
    "Transformation choisie",
    "Transformations possibles",
    "Travelling Settler",
    "Travelling Settler documented",
    "Travelling Settler — possibility to assess",
    "Two sets of plans remain open side by side; neither alone determines the convoy’s future shape.",
    "Under Welcoming Load",
    "Une rafale force le sas extérieur. Veille-Basse est avertie : sans intervention, ses deux équipes ne pourront pas maintenir simultanément les filtres, les archives et l’accueil.",
    "Use case: wide 16:9 story-event illustration for the premium narrative game “Lanternes de cendre”. Create one production-ready character-and-environment image. The attached Cité-Caravane image is a style and world reference only: match its elevated oblique industrial setting, painterly-realistic detail, charcoal/ash blue-black palette, restrained warm amber lantern light, and desolate ash-storm atmosphere. New scene: Ilyana Voss, a practical adult convoy companion in ash-dark work clothes, stands at High Well’s large water distribution valve, one hand near the brass control wheel. Beside her lies an open blank registry with visible ruled pages but absolutely no readable writing. Across the valve table, several local delegates and convoy witnesses face her, making the tension between entrusting her as guarantor and retaining collective arbitration visually clear. Include cistern pipes and the well infrastructure behind them. Respectful non-glamourized character depiction, cinematic wide composition, high environmental storytelling, no readable text, no typography, no logos, no watermark, no weapons, no UI. Do not copy the exact composition of the reference.",
    "Use case: wide 16:9 story-event illustration for the premium narrative game “Lanternes de cendre”. Create one production-ready environment image. The attached Cité-Caravane image is a style and world reference only: match its elevated oblique viewpoint, intricate industrial machinery, painterly-realistic detail, charcoal/ash blue-black palette, restrained warm amber lantern light, and desolate ash-storm atmosphere. New scene: a sludge confinement yard beside High Well. Thick dark settling sludge is held behind patched metal baffles and portable pipes. In the foreground, an engineering table clearly displays two distinct sets of visual plans without readable writing: one for a compact travelling settler mounted on a caravan chassis, the other for a broad ark-like shelter for displaced families. Mechanics compare the two options, but neither machine is being built yet. Make the two possible transformations visually distinct and the unresolved choice unmistakable. Cinematic wide composition, high environmental storytelling, no readable text, no typography, no logos, no watermark, no weapons, no UI. Do not copy the exact composition of the reference.",
    "Use case: wide 16:9 story-event illustration for the premium narrative game “Lanternes de cendre”. Create one production-ready environment image. The attached Cité-Caravane image is a style and world reference only: match its elevated oblique viewpoint, intricate industrial machinery, painterly-realistic detail, charcoal/ash blue-black palette, restrained warm amber lantern light, and desolate ash-storm atmosphere. New scene: the Basketmakers’ district below High Well, with reed-weaving workshops, drying reed bundles, woven baskets and filter mats, narrow water channels, and a dense ash plume visibly drifting down onto the district from distant settling basins. A few small anonymous workers protect their workshops; the threatened craft community and cause-and-effect of the plume must be visually clear. Cinematic wide composition, high environmental storytelling, no readable text, no typography, no logos, no watermark, no weapons, no UI. Do not copy the exact composition of the reference.",
    "Vanne de répartition",
    "Veille-Basse et l’Hospice du Sillon",
    "Veille-Basse — porte des filtres",
    "Veille-Basse — volumes étanches",
    "Volumes de l’Hospice ouverts",
    "Water Market",
    "Water autonomy threatened",
    "Water negotiation",
    "Water-sharing pledge — to be echoed at the Sluice Council ({moment})",
    "Welcoming Load active",
    "Welcoming them will occupy the teams for ten minutes before two carpentry teams can join the convoy.",
    "What the Settler retains",
    "Wide 16:9 painterly industrial 2D archive vault in Veille-Basse’s dead lighthouse, where physical maps, airflow channels and calibration drums reveal that the ancient network displaced toxic ash from protected cities toward peripheral basins; understandable without a Companion, no readable text, label, UI, logo or watermark.",
    "Wide 16:9 painterly industrial 2D scene of Veille-Basse’s failing sealed gate during an ash gust, with two technician teams bracing filters and Ash Pilgrims asking to open protected space; an explicit warning with a visible possible intervention, no text, label, UI, logo or watermark.",
    "Wide 16:9 painterly industrial 2D scene of the sealed lower chambers of an extinguished lighthouse at Veille-Basse as an exhausted refugee cohort reaches the crowded inhabited entrance; cold slate exterior, warm amber refuge, readable ensemble, no text, label, UI, logo or watermark.",
    "Wide 16:9 painterly industrial 2D workshop passage where Maëlys Rive offers a sealed survey case while refugee carpentry teams prepare the Hospice du Sillon; grounded ensemble rather than heroic portrait, no text, label, UI, logo or watermark.",
    "airlock reinforcement",
    "archive review",
    "filter maintenance",
    "haut-puits-decanteur.webp",
    "haut-puits-ilyana.webp",
    "haut-puits-vanniers.webp",
    "lecture des archives",
    "maintien des filtres",
    "renfort des sas",
    "veille-basse-archives.webp",
    "veille-basse-cohorte.webp",
    "veille-basse-maelys.webp",
    "veille-basse-porte.webp",
    "À Veille-Basse",
    "Échanger des Matériaux de charpente contre le renfort des techniciens",
    "Échanger un relevé du Phare mobile contre des filtres étanches",
    "Échanges restants",
    "Éclaireurs de Haut-Puits",
    "Équipes de Maëlys maintenues à Veille-Basse",
    "Équipes envoyées sans Maëlys",
    "État dominant",
    "−30 L d’eau ; relation coopérative ; engagement au Conseil des Vannes.",
    "−30 L water; cooperative relationship; Sluice Council pledge."
  ],
  "nomsDAssets": [
    "haut-puits-decanteur.webp",
    "haut-puits-ilyana.webp",
    "haut-puits-vanniers.webp",
    "veille-basse-archives.webp",
    "veille-basse-cohorte.webp",
    "veille-basse-maelys.webp",
    "veille-basse-porte.webp"
  ]
} as const;
