// Ce fichier est généré par npm run content:compile.
export default {
  "version": 1,
  "fragments": [
    "/api/commercial/assets/deversoir-chassis.webp",
    "/api/commercial/assets/deversoir-conseil.webp",
    "/api/commercial/assets/deversoir-ligne-zero.webp",
    "/api/commercial/assets/deversoir-passage.webp",
    "/api/commercial/assets/haut-puits-decanteur.webp",
    "/api/commercial/assets/haut-puits-ilyana.webp",
    "/api/commercial/assets/haut-puits-vanniers.webp",
    "/api/commercial/assets/nacelles-compagnes.webp",
    "/api/commercial/assets/nacelles-deux-rives.webp",
    "/api/commercial/assets/nacelles-frein.webp",
    "/api/commercial/assets/nacelles-trace.webp",
    "/api/commercial/assets/veille-basse-archives.webp",
    "/api/commercial/assets/veille-basse-cohorte.webp",
    "/api/commercial/assets/veille-basse-maelys.webp",
    "/api/commercial/assets/veille-basse-porte.webp",
    "2 teams integrated",
    "2 équipes intégrées",
    "A broken slab exposes an annular Ancient Network conduit. Its markings describe the first legible Zero Line: a buried service route already running toward the Iron Weave.",
    "A convoy enters a metal corridor as a gate closes behind it, with registers of the abandoned places still visible.",
    "A cracked slab reveals an ancient circular conduit beneath ash basins while technicians survey its markings.",
    "A decision without evidence would turn Stewardship into an authority without appeal.",
    "A gloved hand hesitates above the open magnetic brake while bright brass filings fall onto a survey cloth.",
    "A hand on the brake",
    "A vast rolling frame receives settler and ark components in an ash workshop lit by lanterns.",
    "Accord des Puits Libres et des Pèlerins",
    "Accueil étanche durable des déplacés et de leurs métiers.",
    "Across the table, every old curve converges on the same sacrificed territories.",
    "Adapt the airlocks for the Ark for the Displaced",
    "Adapter les sas pour l’Arche des déplacés",
    "Affecter les techniciens au renfort du sas",
    "Afflux de déplacés",
    "Aide reçue",
    "An ash gust strains the outer airlock. Lower Watch is warned: without intervention, its two teams cannot maintain the filters, archives, and welcome at the same time.",
    "Ancient conduit whose closure will condemn the rear",
    "Applied Cohort support: sealed-frame counterweight",
    "Applied Faction support: priority shared cage",
    "Applied Hospice support: filtered relay from the lower branch",
    "Applied support: main winch under controlled load",
    "Appui appliqué : treuil principal sous charge contrôlée",
    "Appui appliqué par la Cohorte : contrepoids de charpente étanche",
    "Appui appliqué par les Factions : cage commune prioritaire",
    "Appui appliqué par l’Hospice : relais filtré de la branche basse",
    "Arbitrage collectif du registre maintenu",
    "Arche des déplacés",
    "Arche des déplacés documentée",
    "Arche des déplacés — possibilité à étudier",
    "Archive room without readable text: engraved maps, conduits, and calibration drums show ash displaced from central lighthouses toward peripheral Basins.",
    "Archives opened — ash displacement documented",
    "Archives ouvertes — déplacement des cendres documenté",
    "Archives scellées",
    "Archives sealed",
    "Archives techniques de Veille-Basse",
    "Ark for the Displaced documented",
    "Ark for the displaced",
    "Around the deep cistern valve, Free Wells delegates and displaced families await the Lantern-Bearer’s decision.",
    "Ash clogs Lower Watch’s filters while High Well holds the last clear reserves. The delegations demand a common rule before the passage opens.",
    "Ash-coated reed baskets mark the drift all the way to the suspended workshops.",
    "Assign the technicians to reinforce the airlock",
    "At Lower Watch",
    "Atelier de Veille-Basse",
    "Atelier du Déversoir",
    "Aucun engagement diplomatique.",
    "Aucun grand projet n’a été choisi ; le châssis conserve plusieurs attaches incompatibles.",
    "Aucune décision",
    "Aucune transformation imposée.",
    "Autonomie de Haut-Puits garantie",
    "Autonomie hydrique menacée",
    "Autour de la vanne de la citerne profonde, les délégués des Puits Libres et les familles déplacées attendent la décision du Porte-Lanterne.",
    "Backflow records copied",
    "Baliser le boîtier et ses témoins",
    "Basins Regional Frame",
    "Basins regional chassis",
    "Basketmakers’ Path",
    "Beneath a cable drum, technicians discover an old magnetic brake connected to a brass plate and mark it without touching it.",
    "Beneath the Black Spillway slabs",
    "Beneath the dead tower, every free bunk already has a name; the choice is which community will carry the newcomers.",
    "Beneath the main drum, an Ancient Network magnetic brake still modulates every load. Its pulses match the registers showing ash historically displaced toward the outskirts.",
    "Black Spillway",
    "Both Colonies appear in the register, including through refusals and empty places.",
    "Both Colonies’ reserves were placed in common",
    "Both approach registers remain open side by side: no delegate can erase the opposite bank.",
    "Both projects require an entire chassis and remain incompatible with a free or instant transformation.",
    "Boues du panache confinées",
    "Bring common maintenance before the Sluice Council",
    "Bring shared passage before the Sluice Council",
    "Cable brake covertly altered",
    "Cable brake publicly retuned",
    "Cable crews appointed by both branches",
    "Cable crews’ mandate unrecognized",
    "Cable crossing reserved",
    "Cableway Magnetic Brake",
    "Cableway Relay",
    "Cableways",
    "Calibration maps show that the Ancient Network protected productive cities and pushed ash toward the Fractured Basins. Its loss of synchronization did not create the mass: it released what the peripheries had always received.",
    "Camp des Digues",
    "Canal bas encombré de filtres usés",
    "Caravan-city",
    "Ce choix se tranche dans l’Événement narratif associé.",
    "Ce que retient le Décanteur",
    "Chaque siège correspond à une réserve, une dette ou une absence vérifiable.",
    "Charge d’accueil active",
    "Charpente étanche",
    "Chemin des Vanniers",
    "Chosen transformation",
    "Châssis régional des Bassins",
    "Cistern-sharing pact",
    "Citerne profonde de Haut-Puits",
    "Clore le châssis en Plateforme standard et conserver les gabarits",
    "Close Lower Watch’s quarters",
    "Close the chassis as a Standard Platform and preserve the templates",
    "Coffret confié à Maëlys",
    "Coffret de Maëlys confié au convoi",
    "Cohort at the gates",
    "Cohort redirected to Sillon Hospice",
    "Cohorte aux portes",
    "Cohorte du Sillon",
    "Cohorte du Sillon accueillie",
    "Cohorte du Sillon refusée",
    "Cohorte redirigée vers l’Hospice du Sillon",
    "Collective registry arbitration retained",
    "Colonies : Haut-Puits est {hautPuitsStatut} ({hautPuitsDevenir}) ; Veille-Basse est {veilleBasseStatut}, son Hospice est {hospiceDevenir} et la destination de la Cohorte est {cohorteDestination}.",
    "Colonies: High Well is {hautPuitsStatut} ({hautPuitsDevenir}); Lower Watch is {veilleBasseStatut}, its Hospice is {hospiceDevenir}, and the Cohort’s destination is {cohorteDestination}.",
    "Common maintenance prepared for the Council",
    "Complete trade",
    "Conclure l’échange",
    "Conduit ancien dont la fermeture condamnera l’arrière",
    "Conduite de la Ligne Zéro",
    "Confier à Maëlys le relevé de l’Hospice",
    "Confiner les boues avec les équipes du convoi",
    "Conseil des Vannes",
    "Consigner chaque abandon et chaque occasion",
    "Consigner le frein dans le Journal causal",
    "Consigner le procédé du Décanteur itinérant",
    "Contain the sludge with convoy crews",
    "Contraindre les vannes et assumer la coercition",
    "Contrepoids partagés entre les deux rives",
    "Convoquer chaque délégation autour de la table",
    "Cooperative",
    "Coopérative",
    "Copier les registres dans le Journal causal",
    "Copy the records into the causal Journal",
    "Counterweights shared between both banks",
    "Coupe du Phare éteint de Veille-Basse : la Cohorte attend devant les volumes étanches où habitants et Pèlerins préparent des couchettes.",
    "Covertly alter the revealed brake",
    "Coût connu : 12 Matériaux et le châssis entier ; cette forme suivra durablement le convoi et limitera ses remplacements.",
    "Coût connu : 2 Matériaux ; une Trace persistante pourra nourrir doute, accusation ou preuve.",
    "Coût connu : 4 Matériaux renforcent les cages communes ; aucun choix antérieur n’est annulé.",
    "Coût connu : 6 Matériaux et un accord public des Nacelliers.",
    "Coût connu : 8 L d’Eau compensent l’attente imposée aux voyageurs des deux rives.",
    "Coût connu : Ilyana restera consultée, mais sa garantie ne sera pas reconnue.",
    "Coût connu : Veille-Basse perd temporairement une technicienne de ses filtres.",
    "Coût connu : Veille-Basse reste fragile, mais la Pression d’accueil se déplace vers l’Hospice.",
    "Coût connu : aucun camp ne pourra dissimuler sa fragilité après le Conseil.",
    "Coût connu : aucun démontage ne renforcera le convoi avant le passage.",
    "Coût connu : chaque Colonie cédera périodiquement une équipe au Relais.",
    "Coût connu : dix-huit Habitants à abriter immédiatement ; deux équipes seulement après l’intégration.",
    "Coût connu : la Cité-caravane n’emporte qu’un relevé synthétique, mais la révélation reste acquise.",
    "Coût connu : la Cohorte restera sur les routes et ce refus reviendra aux portes de la Colonie.",
    "Coût connu : le Marché des filtres et l’ouverture des archives attendront.",
    "Coût connu : le châssis gagne trois Emplacements ordinaires mais renonce à porter un Projet majeur dans cette Région.",
    "Coût connu : le convoi emporte une dette publique envers les lieux quittés.",
    "Coût connu : le relevé de l’Hospice sera plus lent, sans bloquer sa consolidation.",
    "Coût connu : le relevé sera public et le Déversoir saura ce que vous emportez.",
    "Coût connu : le renseignement quitte le cercle des seuls techniciens, sans déclencher d’opération.",
    "Coût connu : les Bassins conserveront leurs propres preuves et pourront contester votre récit.",
    "Coût connu : les Colonies entendront aussi les options qu’elles refusent.",
    "Coût connu : les Nacelliers sauront exactement quelle infrastructure a été désignée.",
    "Coût connu : les Puits Libres porteront cette nouvelle nuisance au Conseil des Vannes.",
    "Coût connu : les familles déplacées seront écartées jusqu’au Conseil des Vannes.",
    "Coût connu : les priorités de passage devront rester publiques et contestables.",
    "Coût connu : les résidus occuperaient de la Charge et exigeraient un confinement durable.",
    "Coût connu : les équipes d’Entretien délaisseront un chantier pendant la prochaine veille.",
    "Coût connu : l’Hospice portera la Charge et demandera ensuite des places filtrées.",
    "Coût connu : l’accueil augmenterait immédiatement les besoins en Eau, Vivres et Chaleur.",
    "Coût connu : l’occasion sera consignée comme ignorée ; Veille-Basse deviendra perdue au prochain Jalon local.",
    "Coût connu : sa parole engagera personnellement l’Intendance au Conseil des Vannes.",
    "Coût connu : trente litres d’Eau du convoi soutiendront la première distribution.",
    "Coût connu : une équipe technique quitte les filtres le temps de sécuriser la copie.",
    "Cracked slabs beneath moving ash",
    "Create a Welcoming Load in the caravan-city",
    "Create a single 16:9 narrative event illustration for the French dieselpunk survival management game “Les Lanternes de Cendre”. Scene: two suspended industrial cable-car cages face each other above a vast cracked ash-settling basin; travellers from a deep-well settlement and refugees from a sealed lighthouse settlement visibly cooperate to redistribute heavy counterweights. A mobile lighthouse-convoy glows faintly in the distant haze. Art direction: painterly editorial concept art, muted charcoal, ash beige, oxidized copper and restrained amber light; human-scale, materially plausible machinery, weathered cables and pulleys; sober, tense, compassionate, no heroic pose. Wide composition with clear silhouettes and accessibility-friendly value contrast. No text, no letters, no logos, no UI, no watermark.",
    "Create a single 16:9 narrative event illustration matching the established “Les Lanternes de Cendre” painterly dieselpunk concept-art style. Close narrative scene: an open ancient cableway magnetic brake inside a worn industrial relay; a gloved hand hesitates above the exact mechanism while bright brass filings fall onto a dark survey cloth, leaving an unmistakable persistent trace. In the background, two cable crews wait in tense silhouette, making the ethical choice between public repair and covert alteration legible without melodrama. Muted charcoal, ash beige, oxidized copper, controlled amber task light; materially plausible machinery, strong value contrast, sober and morally tense. No text, no letters, no logos, no UI, no watermark.",
    "Create a single 16:9 narrative event illustration matching the established “Les Lanternes de Cendre” painterly dieselpunk concept-art style. Scene on a high cableway relay footbridge over ash basins: two competent women stand side by side but retain distinct roles—an older dark-haired steward named Ilyana holds an open water-sharing register, while a younger field engineer named Maëlys carries a compact weathered survey case. They face heavy cables stretching toward two different settlement banks and calmly compare proposals; cable crews work behind them. No heroic pose, no romance, no authority tableau: collaborative disagreement and practical trust. Muted charcoal, ash beige, oxidized copper, restrained amber beacon light; windblown ash, strong readable silhouettes and value contrast. No text, no legible writing, no letters, no logos, no UI, no watermark.",
    "Create a single 16:9 narrative event illustration matching the established “Les Lanternes de Cendre” painterly dieselpunk concept-art style. Scene: beneath the main drum of an old industrial cableway relay, technicians discover a precise ancient magnetic brake connected to a patterned brass plate; they mark and measure the housing without touching it. Massive pulleys and worn steel cables frame the machinery, ash dust hangs in the air, dim amber work lamps reveal the concrete target. Palette: muted charcoal, ash beige, oxidized copper, restrained amber; sober archaeological-industrial mystery, materially plausible, strong readable silhouettes and value contrast. No text, no letters, no logos, no UI, no watermark.",
    "Crews compare contained sludge with plans for a Travelling Settler and an Ark for the Displaced.",
    "Cross-checked registers from High Well, Lower Watch and the Cableways",
    "Crossing disputed by both Factions",
    "Créer une Charge d’accueil dans la Cité-caravane",
    "Cutaway of Lower Watch’s dead lighthouse: the Cohort waits before sealed rooms where residents and Pilgrims prepare bunks.",
    "Câbles fatigués et contrepoids incomplets",
    "Câbles fatigués mais contrepoids coordonnés",
    "Câbles fatigués sous charge non répartie",
    "Dalles fendues sous une cendre mobile",
    "Dans le sas de Veille-Basse, deux techniciens retiennent une porte sous la cendre tandis que les Pèlerins montrent les volumes protégés encore accessibles.",
    "Dans un atelier couvert, Maëlys tend un coffret de relevés au Porte-Lanterne tandis que des équipes de charpente renforcent l’Hospice au second plan.",
    "Dated readings link the plume to the last Route Commitment; the diversion remains passable, but there is no normal return.",
    "Decision made before irreversible passage into the Iron Weave.",
    "Decision made before the Black Spillway’s revealed conduit.",
    "Decision made before the frame built to carry the regional transformation.",
    "Decision made during the storm saturating both Colonies’ filters.",
    "Decision of the Sluice Council summoned by the Black Spillway storm.",
    "Decision pending",
    "Decline to intervene before the next gust",
    "Deep ruts",
    "Dernier relevé transmis par les Nacelliers",
    "Des paniers de roseaux enduits de cendre balisent la dérive jusqu’aux ateliers suspendus.",
    "Des équipes comparent des boues confinées aux plans d’un Décanteur itinérant et d’une Arche des déplacés.",
    "Deux jeux de plans restent ouverts côte à côte ; aucun ne désigne à lui seul la forme future du convoi.",
    "Deux nacelles suspendues se font face au-dessus d’un bassin de cendre, entourées de voyageurs de Haut-Puits et de Veille-Basse qui répartissent les contrepoids.",
    "Deux voix dans le câble",
    "Dike Camp",
    "Diplomatic commitments",
    "Displaced People’s Ark",
    "Displaced People’s Ark — possibility to assess",
    "Displaced influx",
    "Distribute the counterweights between both banks",
    "Distribution valve",
    "Divert the plume towards the empty basin",
    "Dix-huit personnes du camp des Digues atteignent Veille-Basse. Épuisée mais formée à la charpente étanche, la Cohorte du Sillon demande une destination durable tandis que la Colonie fragile manque déjà de filtres.",
    "Dominant condition",
    "Durable sealed shelter for displaced people and their trades.",
    "During the storm at the Black Spillway",
    "Décanteur itinérant",
    "Décanteur itinérant documenté",
    "Décanteur itinérant — possibilité à étudier",
    "Décision du Conseil des Vannes convoqué par la tempête du Déversoir Noir.",
    "Décision en attente",
    "Décision prise avant le passage irréversible vers la Trame de Fer.",
    "Décision prise devant la conduite révélée du Déversoir Noir.",
    "Décision prise devant le châssis destiné à porter la transformation régionale.",
    "Décision prise pendant la tempête qui sature les filtres des deux Colonies.",
    "Dériver le panache vers le bassin vide",
    "Déversoir Noir",
    "Déversoir sans contrôle établi",
    "Eau, Cohorte et passage régional",
    "Eighteen people from the Dike Camp reach Lower Watch. Exhausted but trained in sealed-frame carpentry, the Sillon Cohort asks for a lasting destination while the fragile Colony is already short of filters.",
    "Elle pose le coffret entre vous, sans présenter sa propre présence comme le prix du succès.",
    "Elle pose son crayon sur le registre plutôt que sur la vanne, laissant la décision au Porte-Lanterne.",
    "En attente",
    "En mission à l’Hospice du Sillon",
    "Engagement de partage de l’eau — écho prévu au Conseil des Vannes ({moment})",
    "Engagements diplomatiques",
    "Entrust her with the sharing register",
    "Entrust the Hospice survey to Maëlys",
    "Essential revelation",
    "Every seat corresponds to a verifiable reserve, debt or absence.",
    "Exhausted",
    "Families turned away",
    "Familles écartées",
    "Fast survey in progress",
    "Fermer les volumes de Veille-Basse",
    "Filter parts",
    "Filtered spaces",
    "Filtres saturés",
    "Force the sluices and own the coercion",
    "Four delegations surround a round mechanical table while an ash storm strikes the Black Spillway sluices.",
    "Free Wells and Ash Pilgrims agreement",
    "Frein des Nacelles réaccordé publiquement",
    "Frein des Nacelles transformé clandestinement",
    "Frein magnétique balisé comme Cible clandestine",
    "Frein magnétique consigné comme Cible clandestine",
    "Frein magnétique des Nacelles",
    "Garantir d’abord l’autonomie de Haut-Puits",
    "Garantir le partage de l’Eau",
    "Garantir le passage vers l’Hospice du Sillon",
    "Garder Maëlys aux filtres et envoyer les charpentiers",
    "Garder le registre sous arbitrage collectif",
    "Generate a wide narrative-game environment illustration of the Déversoir Noir: a cracked settling basin whose broken wall reveals the buried Ligne Zéro maintenance conduit and its circular mobile-lighthouse docking interface, inspected by cable crews under an ash storm. Match the elevated oblique painterly-industrial direction, charcoal palette and restrained amber light of the supplied world reference. No readable text, typography, logos, watermark, weapons or UI.",
    "Generate a wide narrative-game illustration of the Conseil des Vannes during an ash storm, with delegates around a mechanical sluice table and four physically legible courses of action: shared cistern valves, settler repair parts, sealed refugee frames and a chained coercive gate. Match the supplied world reference without copying it. No readable text, typography, logos, watermark, weapons or UI.",
    "Generate a wide narrative-game illustration of the irreversible Passage de région: the Cité-Caravane enters a buried Ligne Zéro corridor while the ash Front closes behind, with physical lantern tokens recalling High Well, Lower Watch, the cable gondolas and the black sluice. Match the supplied world reference. No readable text, typography, logos, watermark, weapons or UI.",
    "Generate a wide narrative-game worksite illustration where one finite regional chassis is committed either to a travelling settling apparatus or to sealed Ark frames for displaced people, with unchosen plans preserved nearby. Match the supplied elevated oblique painterly-industrial world reference. No readable text, typography, logos, watermark, weapons or UI.",
    "Guarantee High Well’s autonomy first",
    "Guarantee Water sharing",
    "Guarantee passage to Sillon Hospice",
    "Habitants de Veille-Basse",
    "Hand the registers to the people who remain",
    "Haut-Puits garde une garante et un pacte dont les effets survivront à votre départ.",
    "Haut-Puits reste stable ; la relation publique se ferme.",
    "Help received",
    "Her proposal defends her belief in safe Water for everyone without granting her authority over the Council.",
    "High Well Scouts",
    "High Well autonomy guaranteed",
    "High Well deep cistern",
    "High Well keeps a guarantor and a pact whose effects survive your departure.",
    "High Well remains stable; the public relationship closes.",
    "Hospice du Sillon",
    "Hospice filtered relay",
    "Hospice sealed quarters opened",
    "Hospice survey completed",
    "Ilyana Voss argues for a shared crossing register; Maëlys Rive wants crews able to maintain the cables to move between Colonies. They frame two options compatible with established facts without claiming personal authority.",
    "Ilyana Voss défend un registre commun des passages ; Maëlys Rive veut que les équipes capables d’entretenir les câbles circulent entre les Colonies. Elles formulent deux options compatibles avec les faits acquis, sans réclamer d’autorité personnelle.",
    "Ilyana and Maëlys stand on a cableway footbridge, one holding a register and the other a survey case, facing cables stretched toward both banks.",
    "Ilyana asks that every opening of the cistern record its beneficiaries and cost, even though the Free Wells consider such a register intrusive.",
    "Ilyana at the last valve",
    "Ilyana demande que chaque ouverture de la citerne soit consignée avec ses bénéficiaires et son coût, même si les Puits Libres jugent ce registre intrusif.",
    "Ilyana devant la dernière vanne",
    "Ilyana et Maëlys se tiennent sur une passerelle de nacelles, l’une avec un registre et l’autre avec un coffret de relevés, face aux câbles tendus vers les deux rives.",
    "Ilyana garante du registre",
    "Ilyana guarantees the registry",
    "Ilyana holds an open register before the High Well valve while delegates await the decision.",
    "Ilyana links the shared-crossing proposal to the water commitments made at High Well.",
    "Ilyana recommande la seule option soutenue par des faits publics et une responsabilité durable.",
    "Ilyana recommends the sole option backed by public facts and durable responsibility.",
    "Ilyana relie la proposition de passage partagé aux engagements hydriques pris à Haut-Puits.",
    "Ilyana tient un registre ouvert devant la vanne de Haut-Puits tandis que les délégués attendent la décision.",
    "In Lower Watch’s airlock, two technicians hold a gate against the ash while Pilgrims point toward protected rooms still available.",
    "In a covered workshop, Maëlys offers the Lantern-Bearer a survey case while carpentry teams reinforce the Hospice in the background.",
    "Interface relevée par les techniciens du Déversoir",
    "Interface surveyed by the Spillway technicians",
    "Intervention à Veille-Basse refusée",
    "Intégration",
    "Iron Weave Verge",
    "Isolated cable crews at the Relay",
    "Keep Maëlys on the filters and send the carpenters",
    "Keep the register under collective arbitration",
    "Known cost: 12 Materials and the whole chassis; this shape will follow the convoy and restrict later replacements.",
    "Known cost: 2 Materials; a persistent Trace may later support doubt, accusation or proof.",
    "Known cost: 4 Materials reinforce the shared cages; no earlier choice is undone.",
    "Known cost: 6 Materials and the Cable Crews’ public agreement.",
    "Known cost: 8 L of Water offset the wait imposed on travellers from both banks.",
    "Known cost: Ilyana will remain consulted, but her guarantee will not be recognized.",
    "Known cost: Lower Watch remains fragile, but the welcoming Pressure shifts to the Hospice.",
    "Known cost: Lower Watch temporarily loses one filter technician.",
    "Known cost: Maintenance crews will leave one worksite unattended during the next watch.",
    "Known cost: crossing priorities must remain public and open to challenge.",
    "Known cost: displaced families will be turned away until the Sluice Council.",
    "Known cost: each Colony will periodically assign one crew to the Relay.",
    "Known cost: her word will personally commit Stewardship at the Sluice Council.",
    "Known cost: neither camp can conceal its fragility after the Council.",
    "Known cost: no dismantled part will reinforce the convoy before passage.",
    "Known cost: one technical team leaves the filters while securing the copy.",
    "Known cost: residues would occupy Load and require lasting containment.",
    "Known cost: shelter eighteen inhabitants immediately; gain two teams only after integration.",
    "Known cost: sheltering people would immediately increase Water, Food and Heat needs.",
    "Known cost: the Basins retain their own evidence and can challenge your account.",
    "Known cost: the Cable Crews will know exactly which infrastructure was designated.",
    "Known cost: the Cohort remains on the roads and this refusal will return to the Colony’s gates.",
    "Known cost: the Colonies will also hear the options they reject.",
    "Known cost: the Free Wells will bring this new burden to the Sluice Council.",
    "Known cost: the Hospice carries the Load and will later ask for filtered spaces.",
    "Known cost: the Hospice survey will be slower without blocking its reinforcement.",
    "Known cost: the caravan-city carries only a summary survey, but the revelation remains known.",
    "Known cost: the chassis gains three ordinary Slots but gives up carrying a Major Project in this Region.",
    "Known cost: the convoy carries a public debt to the places it leaves.",
    "Known cost: the filter market and archive opening must wait.",
    "Known cost: the intelligence leaves the technicians’ circle without launching an operation.",
    "Known cost: the opportunity will be recorded as ignored; Lower Watch will become lost at the next local Milestone.",
    "Known cost: the survey will be public and the Spillway will know what you carry.",
    "Known cost: thirty litres of convoy Water will support the first distribution.",
    "La Cible révélée peut être réparée au grand jour ou transformée sans consentement pour rendre les charges impossibles à discriminer. L’opération cachée toucherait une infrastructure précise et laisserait une enquête possible.",
    "La Cohorte a été réorientée vers une Arche de déplacés",
    "La Cohorte vient du camp des Digues, compte dix-huit personnes et sait rendre habitables des volumes fissurés.",
    "La capacité habitable du châssis ne peut plus être réaffectée.",
    "La cendre sature les filtres de Veille-Basse tandis que Haut-Puits garde les dernières réserves claires. Les délégations réclament une règle commune avant l’ouverture du passage.",
    "La conduite de la Ligne Zéro a été préservée",
    "La conduite zéro",
    "La main sur le frein",
    "La maintenance commune portée depuis les Nacelles garantit déjà des équipes au Relais ; chaque Colonie devra désormais honorer cette obligation.",
    "La négociation est tranchée.",
    "La place sous le Phare éteint",
    "La plaque de laiton porte le même motif que les courbes de reflux copiées à Veille-Basse.",
    "La porte des filtres",
    "La rive basse n’envoie ni coffret ni équipe : le refus d’intervenir à Veille-Basse revient comme une place vide dans chaque cage.",
    "La tempête aux vannes",
    "La transformation régionale a été scellée",
    "Laisser les originaux sous la garde de Veille-Basse",
    "Latest survey relayed by the Cable Crews",
    "Le Journal gardera ces absences comme causes disponibles pour les rapports et l’épilogue ; le passage de Région, lui, ne sera pas annulable.",
    "Le Réseau ancien déplaçait la cendre vers les périphéries",
    "Le boîtier, son alimentation et sa transmission sont localisés : le frein magnétique est désormais une Cible clandestine concrète, limitée à ce passage.",
    "Le capot reste ouvert devant vous ; la différence entre réparation et intervention cachée est explicite.",
    "Le châssis des Bassins",
    "Le coffret confié à Maëlys documente les charges de la rive basse : sa mission donne aux techniciens de Veille-Basse une voix dans la répartition.",
    "Le coffret contient des jauges anciennes et un protocole que Maëlys a reconstruit, mais aucune étape ne requiert sa présence.",
    "Le coût réellement payé pour atteindre le Relais porte déjà la marque des deux Colonies, de la Cohorte, du panache et de leurs Factions.",
    "Le frein sous la cendre",
    "Le halo du convoi a poussé une langue de cendre vers les ateliers des Vanniers. Haut-Puits demande qui portera les boues nécessaires à son confinement.",
    "Le pacte des citernes",
    "Le panache du Phare dérive vers l’est et atteint les Vanniers.",
    "Le partage, la réparation du décanteur et la réorientation de la Cohorte ne seront proposés que si vos décisions antérieures les rendent réels. La contrainte restera explicite.",
    "Le passage sans retour",
    "Le poids des deux rives",
    "Le refus de Veille-Basse revient sous la forme d’un filtre vide et d’une délégation sans équipe.",
    "Le registre confié à Ilyana précède le convoi sur le câble : les Nacelliers traitent la garantie de partage de Haut-Puits comme une parole opposable.",
    "Le registre de jauge confirme que le partage rendrait Haut-Puits fragile sans assécher immédiatement la citerne.",
    "Le registre resté collectif arrive sans garante désignée : les Nacelliers exigent que chaque priorité de Haut-Puits soit renégociée au Relais.",
    "Le signal étouffé au départ manque dans la séquence ; l’interface indique précisément cette lacune.",
    "Le vieux décanteur a été retenu comme transformation du convoi",
    "Leave the originals in Lower Watch’s care",
    "Les Puits Libres proposent d’ouvrir la citerne aux familles déplacées si la cité-caravane garantit des pièces de filtration jusqu’au Conseil des Vannes.",
    "Les Vanniers",
    "Les Vanniers sous le panache",
    "Les abandons ont été consignés avant le passage",
    "Les accès arrière du Déversoir seront condamnés dès l’engagement du convoi. Avant de quitter les Bassins, le Conseil nomme les lieux abandonnés, les colonies fragilisées et les occasions encore ouvertes.",
    "Les ateliers des Vanniers apparaissent sous un panache de cendre balisé par des paniers de roseaux.",
    "Les ateliers traduisent la décision du Conseil en bâtis transportables. Le décanteur ou l’arche deviendra une transformation majeure du convoi, jamais une réponse finale à la Trame.",
    "Les boues confinées prouvent qu’un Décanteur itinérant sécuriserait des sources contaminées, tandis que les plans de sas pourraient servir à une Arche des déplacés.",
    "Les bras du vieux décanteur dessinent une purification mobile à l’échelle du convoi.",
    "Les cartes de calibration montrent que le Réseau ancien protégeait les villes productives et repoussait la cendre vers les Bassins fendus. Sa désynchronisation n’a pas créé la masse : elle a libéré ce que les périphéries recevaient déjà.",
    "Les comptes d’eau ont été rendus publics",
    "Les deux Colonies apparaissent dans le registre, y compris par leurs refus et leurs places vides.",
    "Les deux Compagnes parlent depuis des rives différentes, puis nouent leurs propositions au même câble.",
    "Les deux projets réclament un châssis entier et restent incompatibles avec une transformation gratuite ou instantanée.",
    "Les délégations ont été convoquées aux Vannes",
    "Les gabarits régionaux ont été conservés",
    "Les marques de niveau traversent la paroi de la citerne comme les anneaux d’une dette ancienne.",
    "Les membrures de l’Arche réservent des travées aux déplacés et à leurs métiers.",
    "Les nacelles ne peuvent porter à la fois les réserves de Haut-Puits et toutes les familles venues de Veille-Basse. Les Puits Libres et les Pèlerins réclament chacun la priorité promise en amont.",
    "Les plans écartés restent lisibles : ils pourront revenir dans un rapport, une dette ou une autre construction.",
    "Les registres des Bassins ont été transmis",
    "Les registres du reflux",
    "Les registres d’approche restent ouverts côte à côte : aucun délégué ne peut effacer la rive opposée.",
    "Les relevés datés relient le panache au dernier Engagement de route ; le détour reste praticable, mais sans retour normal.",
    "Les repères alternent ventilation, délestage et accès de service.",
    "Les réserves des deux Colonies ont été mises en partage",
    "Les réserves, le décanteur et la Cohorte ne sont défendables que s’ils ont été préparés dans les Colonies.",
    "Les techniciens confirment deux réponses viables avant la prochaine rafale ; aucune perte n’est encore irréversible.",
    "Les techniciens isolent une interface encore exploitable. Son relevé donnera une avance concrète sur les accès de la prochaine Région.",
    "Les tracés, dates de maintenance et volumes déplacés se recoupent ; cette révélation ne dépend du témoignage d’aucun Compagnon.",
    "Les vannes ont été contraintes au nom du passage",
    "Les verrous vibrent ; entre les deux rafales demeure une fenêtre assez longue pour agir.",
    "Les équipes gardées à Veille-Basse ne peuvent renforcer les câbles : leur absence rend visible le prix de la priorité donnée à la Colonie.",
    "Level marks cross the cistern wall like the rings of an old debt.",
    "Levées instables sous la tempête de cendre",
    "Lieux non rejoints : {lieux}.",
    "Lieux traversés puis quittés : {lieux}.",
    "Lisière de la Trame de Fer",
    "Local pressures",
    "Loss announced — intervention opportunity",
    "Low canal cluttered with spent filters",
    "Lower Watch airlock reinforced",
    "Lower Watch and Sillon Hospice",
    "Lower Watch intervention refused",
    "Lower Watch keeps Maëlys’s mission and the crews whose priority you set.",
    "Lower Watch residents",
    "Lower Watch technical archives",
    "Lower Watch technicians",
    "Lower Watch workshop",
    "Lower Watch — filter gate",
    "Lower Watch — sealed quarters",
    "Lower Watch’s refusal returns as an empty filter and a delegation without a crew.",
    "Lui confier le registre de partage",
    "L’accord porté depuis les Nacelles fournit déjà une procédure de passage contestable.",
    "L’accueil occupera les équipes pendant dix minutes avant que deux équipes de charpente puissent rejoindre le convoi.",
    "L’harmonique consignée au départ réapparaît dans les repères de maintenance.",
    "L’interface de la Ligne Zéro a été relevée",
    "Machinerie sous le Relais",
    "Machinery beneath the Relay",
    "Magnetic brake marked as a Covert Target",
    "Magnetic brake recorded as a Covert Target",
    "Maintenance commune préparée pour le Conseil",
    "Mandat des Nacelliers non reconnu",
    "Marché de besoins",
    "Marché de l’eau",
    "Mark the housing and its telltales",
    "Maëlys Rive",
    "Maëlys Rive, a technician of the dead lighthouse, offers her survey case to inspect the Hospice conduits. Her knowledge opens a more precise route; the carpentry teams can also succeed without her.",
    "Maëlys Rive, technicienne du Phare éteint, propose son coffret de relevés pour reconnaître les conduites de l’Hospice. Son savoir ouvre une voie plus précise ; les équipes de charpente peuvent aussi réussir sans elle.",
    "Maëlys and the sealed case",
    "Maëlys et le coffret étanche",
    "Maëlys links common maintenance to the Cohort’s fate and Lower Watch’s technicians.",
    "Maëlys relie la maintenance commune au devenir de la Cohorte et aux techniciens de Veille-Basse.",
    "Maëlys’s survey case entrusted to the convoy",
    "Maëlys’s teams kept at Lower Watch",
    "Mobile purification of murky water along the road.",
    "Mobile settler",
    "Nacelliers des Vannes",
    "Nacelliers isolés du Relais",
    "Nacelliers mandatés par les deux branches",
    "Narrow airlocks under filtered ash",
    "Needs market",
    "Negotiation open",
    "No decision",
    "No diplomatic commitment.",
    "No established control",
    "No external input image; generated from the written Ilyana Voss and Maëlys Rive companion-story brief.",
    "No external input image; generated from the written Maëlys Rive event brief.",
    "No external input image; generated from the written Nacelles mystery brief.",
    "No external input image; generated from the written Nacelles regional-conflict brief.",
    "No external input image; generated from the written Nacelles systemic-consequence brief.",
    "No external input image; generated from the written Veille-Basse event brief.",
    "No external input image; generated from the written Veille-Basse mystery-revelation brief.",
    "No major project was chosen; the frame keeps several incompatible fittings.",
    "No transformation imposed.",
    "Négociation de l’eau",
    "Négociation ouverte",
    "Occasions encore ouvertes : relevé de la Ligne Zéro {ligneZero} ; transformation régionale {projet} ; archives de Veille-Basse {archives}.",
    "Offer exhausted",
    "Offre épuisée",
    "On mission at Sillon Hospice",
    "One hydraulic team remains assigned to the indivisible chassis.",
    "Open opportunities: Zero Line survey {ligneZero}; regional transformation {projet}; Lower Watch archives {archives}.",
    "Open the Hospice’s filtered chambers",
    "Opening the housing scatters identifiable brass filings; they will survive the regional transition as a Covert Trace.",
    "Ornières profondes",
    "Ouvrir les volumes filtrés de l’Hospice",
    "Pacte de partage des citernes",
    "Panache dérivé vers le bassin vide",
    "Partage organisé",
    "Partager les réserves entre les deux Colonies",
    "Partager l’eau",
    "Passage contesté par les deux Factions",
    "Passage des Nacelles réservé",
    "Passage extérieur au Conseil des Vannes",
    "Passage garanti par l’Hospice",
    "Passage governed by the Sluice Council’s decision",
    "Passage guaranteed by the Hospice",
    "Passage into the Iron Weave",
    "Passage outside the Sluice Council",
    "Passage partagé préparé pour le Conseil",
    "Passage placé sous la décision du Conseil des Vannes",
    "Passage vers la Trame de Fer",
    "Passerelle du Relais",
    "Persistent brass-filings Trace",
    "Perte annoncée — occasion d’intervention",
    "Pièces de filtration",
    "Places crossed and left behind: {lieux}.",
    "Places filtrées",
    "Places not reached: {lieux}.",
    "Plume diverted to the empty basin",
    "Plume sludge contained",
    "Porter la maintenance commune au Conseil des Vannes",
    "Porter le passage partagé au Conseil des Vannes",
    "Possible transformations",
    "Preserve the conduit as the Basins’ lung",
    "Pressions locales",
    "Pressures",
    "Prosperous",
    "Prospère",
    "Protect the reserves",
    "Protéger les réserves",
    "Préserver la conduite comme poumon des Bassins",
    "Public relationship",
    "Publier les réserves et les pertes avant de siéger",
    "Publish reserves and losses before sitting",
    "Purification mobile des eaux troubles sur la route.",
    "Quatre délégations entourent une table mécanique ronde pendant qu’une tempête de cendre frappe les vannes du Déversoir Noir.",
    "Record every abandonment and opportunity",
    "Record the Travelling Settler process",
    "Record the brake in the causal Journal",
    "Records entrusted to Lower Watch",
    "Redirect the Cohort into an Ark for the displaced",
    "Redirected",
    "Redirigée",
    "Registres confiés à Veille-Basse",
    "Registres croisés de Haut-Puits, Veille-Basse et des Nacelles",
    "Registres du reflux copiés",
    "Reinforced",
    "Rejected plans remain legible: they can return in a report, a debt or another construction.",
    "Relais des Nacelles",
    "Relais des Vannes",
    "Relais filtré de l’Hospice",
    "Relais tenu par l’Hospice du Sillon",
    "Relation publique",
    "Relay footbridge",
    "Relay held by Sillon Hospice",
    "Relever l’interface avant de refermer la dalle",
    "Relevé de l’Hospice terminé",
    "Relevé de surface des techniciens du Déversoir",
    "Relevé lent en cours",
    "Relevé non planifié",
    "Relevé rapide en cours",
    "Relevé transmis par la branche d’approche",
    "Remedies for the well crews",
    "Remèdes pour les puisatiers",
    "Renforcé",
    "Renoncer à intervenir avant la prochaine rafale",
    "Repair the old settler as a major project",
    "Reserve the next cage for the convoy",
    "Reserves depleted",
    "Reserves protected",
    "Retune the brake publicly",
    "Roads beyond Lower Watch",
    "Room beneath the dead lighthouse",
    "Routes hors de Veille-Basse",
    "Routes, maintenance dates, and displaced volumes agree; this revelation depends on no Companion’s testimony.",
    "Réaccorder publiquement le frein",
    "Réorienter la Cohorte vers une Arche de déplacés",
    "Réparer le vieux décanteur comme projet majeur",
    "Répartir les contrepoids entre les deux rives",
    "Réserver la prochaine cage au convoi",
    "Réserves entamées",
    "Réserves protégées",
    "Révélation essentielle",
    "Sa proposition défend sa conviction d’une Eau sûre pour tous sans lui donner autorité sur le Conseil.",
    "Salle d’archives sans texte lisible : cartes gravées, conduites et tambours de calibration montrent la cendre déplacée des phares centraux vers les Bassins périphériques.",
    "Sans contrôle établi",
    "Sas de Veille-Basse renforcé",
    "Sas étroits sous une cendre filtrée",
    "Saturated filters",
    "Sceller la transformation retenue dans le châssis",
    "Seal the chosen transformation into the frame",
    "Sealed-frame carpentry",
    "Secondary inhabited site",
    "Seuil de la Trame de Fer",
    "Share the reserves between both Colonies",
    "Share the water",
    "Shared crossing prepared for the Council",
    "Sharing organized",
    "Sharing, repairing the settler and redirecting the Cohort will appear only when earlier decisions make them real. Coercion will remain explicit.",
    "She places her pencil on the register rather than the valve, leaving the decision to the Lantern-Bearer.",
    "She sets the case between you without presenting her own presence as the price of success.",
    "Sillon Cohort",
    "Sillon Cohort refused",
    "Sillon Cohort welcomed",
    "Sillon Hospice",
    "Site habité secondaire",
    "Slow survey in progress",
    "Sluice Cable Crews",
    "Sluice Council",
    "Sluice Relay",
    "Sluice Table",
    "Sous Charge d’accueil",
    "Sous la tour éteinte, chaque couchette libre a déjà un nom ; le choix porte sur la communauté qui assumera les nouveaux arrivants.",
    "Sous le tambour d’une nacelle, des techniciens découvrent un frein magnétique ancien relié à une plaque de laiton et le balisent sans le toucher.",
    "Sous le tambour principal, un frein magnétique du Réseau ancien module encore chaque charge. Ses impulsions concordent avec les registres montrant le déplacement historique de la cendre vers les périphéries.",
    "Sous les dalles du Déversoir Noir",
    "Specialty",
    "Spillway Technicians",
    "Spillway Workshop",
    "Spillway technicians’ surface survey",
    "Spillway under no established control",
    "Spécialité",
    "Summon every delegation around the table",
    "Sur la table, les anciennes courbes convergent toutes vers les mêmes territoires sacrifiés.",
    "Survey case entrusted to Maëlys",
    "Survey not planned",
    "Survey relayed by the approach branch",
    "Survey the interface before closing the slab",
    "Table des Vannes",
    "Teams sent without Maëlys",
    "Techniciens de Veille-Basse",
    "Techniciens du Déversoir",
    "The Ancient Network displaced ash toward the peripheries",
    "The Ark’s ribs reserve bays for displaced people and their trades.",
    "The Basins’ frame",
    "The Basins’ registers were handed on",
    "The Basketmakers",
    "The Basketmakers under the plume",
    "The Basketmakers’ workshops sit beneath an ash plume marked by reed baskets.",
    "The Cohort comes from the Dike Camp, numbers eighteen people, and knows how to make cracked chambers habitable.",
    "The Cohort was redirected into an Ark for the displaced",
    "The Free Wells will open the cistern to displaced families if the caravan-city guarantees filtration parts until the Sluice Council.",
    "The Journal will retain these absences as causes for reports and the epilogue; the regional passage itself cannot be undone.",
    "The Lighthouse plume drifts east and reaches the Basketmakers.",
    "The Spillway’s rear accesses will be condemned once the convoy commits. Before leaving the Basins, the Council names the abandoned places, weakened Colonies and still-open opportunities.",
    "The Zero Conduit",
    "The Zero Line conduit was preserved",
    "The Zero Line interface was surveyed",
    "The abandoned places were recorded before passage",
    "The agreement carried from the Cableways already supplies a challengeable crossing procedure.",
    "The backflow records",
    "The brake beneath the ash",
    "The brass plate bears the same pattern as the reflux curves copied at Lower Watch.",
    "The cableways cannot carry both High Well’s reserves and every family arriving from Lower Watch. The Free Wells and Ash Pilgrims each demand the priority promised upstream.",
    "The case entrusted to Maëlys documents loads from the lower bank: her mission gives Lower Watch technicians a voice in the allocation.",
    "The case holds ancient gauges and a protocol Maëlys reconstructed, but no step requires her presence.",
    "The chassis’ living capacity can no longer be reassigned.",
    "The cistern pact",
    "The collective register arrives without a named guarantor: the cable crews require every High Well priority to be renegotiated at the Relay.",
    "The common maintenance pledge carried from the Cableways already guarantees crews at the Relay; each Colony must now honor that obligation.",
    "The contained sludge proves that a Travelling Settler could secure contaminated sources, while the airlock plans could serve an Ark for the Displaced.",
    "The convoy’s watch halo pushed an ash tongue towards the Basketmakers’ workshops. High Well asks who will carry the sludge needed to contain it.",
    "The cost already paid to reach the Relay bears the mark of both Colonies, the Cohort, the plume and their Factions.",
    "The delegations were summoned to the Sluices",
    "The filter gate",
    "The gauge register confirms that sharing would leave High Well fragile without immediately draining the cistern.",
    "The harmonic recorded at departure returns among the maintenance marks.",
    "The housing remains open before you; the difference between repair and hidden intervention is explicit.",
    "The housing, power feed and transmission are located: the magnetic brake is now a concrete Covert Target limited to this crossing.",
    "The locks shake; between two gusts, a window long enough to act remains.",
    "The lower bank sends neither case nor crew: refusing to intervene at Lower Watch returns as an empty place in every cage.",
    "The markings alternate ventilation, load shedding and service access.",
    "The negotiation is settled.",
    "The old settler was chosen as a convoy transformation",
    "The old settler’s arms outline mobile purification at convoy scale.",
    "The passage without return",
    "The regional templates were preserved",
    "The regional transformation was sealed",
    "The register entrusted to Ilyana reaches the cable crews first: they treat High Well’s sharing guarantee as a commitment that can be challenged.",
    "The repository Cité-Caravane illustration was supplied only as a visual world and style reference.",
    "The reserves, settler and Cohort can be defended only if they were prepared in the Colonies.",
    "The revealed Target can be repaired openly or altered without consent so loads can no longer be discriminated. The hidden operation would affect a precise infrastructure and leave room for an investigation.",
    "The signal smothered at departure is missing from the sequence; the interface identifies the gap.",
    "The sluices were forced in the name of passage",
    "The storm at the sluices",
    "The teams kept at Lower Watch cannot reinforce the cables: their absence exposes the cost of prioritizing the Colony.",
    "The technicians confirm two viable responses before the next gust; no loss is irreversible yet.",
    "The technicians isolate a usable interface. Surveying it will provide concrete intelligence on the next Region’s access points.",
    "The two Companions speak from different banks, then knot their proposals to the same cable.",
    "The water accounts were made public",
    "The weight of both banks",
    "The workshops translate the Council’s decision into transportable frames. The settler or the Ark will become a major convoy transformation, never a final answer to the Iron Weave.",
    "This choice is settled in the associated narrative Event.",
    "Threshold of the Iron Weave",
    "Toute ouverture du boîtier disperse une limaille de laiton identifiable ; elle survivra au changement de Région comme Trace clandestine.",
    "Trace de limaille de laiton persistante",
    "Trade a mobile Lighthouse survey for sealed filters",
    "Trade framing Materials for technician support",
    "Trades remaining",
    "Transactional",
    "Transactionnelle",
    "Transformation choisie",
    "Transformations possibles",
    "Transformer clandestinement le frein révélé",
    "Transmettre les registres aux habitants qui restent",
    "Travelling Settler",
    "Travelling Settler documented",
    "Travelling Settler — possibility to assess",
    "Two sets of plans remain open side by side; neither alone determines the convoy’s future shape.",
    "Two suspended cable cages face one another above an ash basin while travellers from High Well and Lower Watch distribute counterweights.",
    "Two voices in the cable",
    "Un convoi entre dans un corridor de métal tandis qu’une porte se ferme derrière lui et que des registres des lieux quittés restent visibles.",
    "Un vaste châssis roulant reçoit des éléments de décanteur et d’arche dans un atelier de cendre éclairé par des lanternes.",
    "Under Welcoming Load",
    "Une dalle fendue révèle une conduite circulaire ancienne sous les bassins de cendre, entourée de techniciens qui en relèvent les repères.",
    "Une dalle rompue découvre un conduit annulaire du Réseau ancien. Ses repères décrivent la première Ligne Zéro lisible : un service enfoui qui file déjà vers la Trame de Fer.",
    "Une décision sans preuve ferait de l’Intendance une autorité sans recours.",
    "Une main gantée hésite au-dessus du frein magnétique ouvert tandis que de la limaille de laiton brillante tombe sur un tissu de relevé.",
    "Une rafale force le sas extérieur. Veille-Basse est avertie : sans intervention, ses deux équipes ne pourront pas maintenir simultanément les filtres, les archives et l’accueil.",
    "Une équipe hydraulique reste affectée au châssis indivisible.",
    "Unstable embankments beneath the ash storm",
    "Use case: wide 16:9 story-event illustration for the premium narrative game “Lanternes de cendre”. Create one production-ready character-and-environment image. The attached Cité-Caravane image is a style and world reference only: match its elevated oblique industrial setting, painterly-realistic detail, charcoal/ash blue-black palette, restrained warm amber lantern light, and desolate ash-storm atmosphere. New scene: Ilyana Voss, a practical adult convoy companion in ash-dark work clothes, stands at High Well’s large water distribution valve, one hand near the brass control wheel. Beside her lies an open blank registry with visible ruled pages but absolutely no readable writing. Across the valve table, several local delegates and convoy witnesses face her, making the tension between entrusting her as guarantor and retaining collective arbitration visually clear. Include cistern pipes and the well infrastructure behind them. Respectful non-glamourized character depiction, cinematic wide composition, high environmental storytelling, no readable text, no typography, no logos, no watermark, no weapons, no UI. Do not copy the exact composition of the reference.",
    "Use case: wide 16:9 story-event illustration for the premium narrative game “Lanternes de cendre”. Create one production-ready environment image. The attached Cité-Caravane image is a style and world reference only: match its elevated oblique viewpoint, intricate industrial machinery, painterly-realistic detail, charcoal/ash blue-black palette, restrained warm amber lantern light, and desolate ash-storm atmosphere. New scene: a sludge confinement yard beside High Well. Thick dark settling sludge is held behind patched metal baffles and portable pipes. In the foreground, an engineering table clearly displays two distinct sets of visual plans without readable writing: one for a compact travelling settler mounted on a caravan chassis, the other for a broad ark-like shelter for displaced families. Mechanics compare the two options, but neither machine is being built yet. Make the two possible transformations visually distinct and the unresolved choice unmistakable. Cinematic wide composition, high environmental storytelling, no readable text, no typography, no logos, no watermark, no weapons, no UI. Do not copy the exact composition of the reference.",
    "Use case: wide 16:9 story-event illustration for the premium narrative game “Lanternes de cendre”. Create one production-ready environment image. The attached Cité-Caravane image is a style and world reference only: match its elevated oblique viewpoint, intricate industrial machinery, painterly-realistic detail, charcoal/ash blue-black palette, restrained warm amber lantern light, and desolate ash-storm atmosphere. New scene: the Basketmakers’ district below High Well, with reed-weaving workshops, drying reed bundles, woven baskets and filter mats, narrow water channels, and a dense ash plume visibly drifting down onto the district from distant settling basins. A few small anonymous workers protect their workshops; the threatened craft community and cause-and-effect of the plume must be visually clear. Cinematic wide composition, high environmental storytelling, no readable text, no typography, no logos, no watermark, no weapons, no UI. Do not copy the exact composition of the reference.",
    "Vanne de répartition",
    "Veille-Basse et l’Hospice du Sillon",
    "Veille-Basse garde la mission de Maëlys et les équipes dont vous avez fixé la priorité.",
    "Veille-Basse — porte des filtres",
    "Veille-Basse — volumes étanches",
    "Volumes de l’Hospice ouverts",
    "Water Market",
    "Water autonomy threatened",
    "Water negotiation",
    "Water, Cohort and regional passage",
    "Water-sharing pledge — to be echoed at the Sluice Council ({moment})",
    "Welcoming Load active",
    "Welcoming them will occupy the teams for ten minutes before two carpentry teams can join the convoy.",
    "What the Settler retains",
    "Wide 16:9 painterly industrial 2D archive vault in Veille-Basse’s dead lighthouse, where physical maps, airflow channels and calibration drums reveal that the ancient network displaced toxic ash from protected cities toward peripheral basins; understandable without a Companion, no readable text, label, UI, logo or watermark.",
    "Wide 16:9 painterly industrial 2D scene of Veille-Basse’s failing sealed gate during an ash gust, with two technician teams bracing filters and Ash Pilgrims asking to open protected space; an explicit warning with a visible possible intervention, no text, label, UI, logo or watermark.",
    "Wide 16:9 painterly industrial 2D scene of the sealed lower chambers of an extinguished lighthouse at Veille-Basse as an exhausted refugee cohort reaches the crowded inhabited entrance; cold slate exterior, warm amber refuge, readable ensemble, no text, label, UI, logo or watermark.",
    "Wide 16:9 painterly industrial 2D workshop passage where Maëlys Rive offers a sealed survey case while refugee carpentry teams prepare the Hospice du Sillon; grounded ensemble rather than heroic portrait, no text, label, UI, logo or watermark.",
    "Worn cables and incomplete counterweights",
    "Worn cables under an unbalanced load",
    "Worn cables with coordinated counterweights",
    "Zero Line Conduit",
    "abandoned",
    "abandonné",
    "absorbed",
    "airlock reinforcement",
    "archive review",
    "carried forward for the Iron Weave",
    "deversoir-chassis.webp",
    "deversoir-conseil.webp",
    "deversoir-ligne-zero.webp",
    "deversoir-passage.webp",
    "désormais consultables",
    "emporté vers la Trame de Fer",
    "filter maintenance",
    "haut-puits-decanteur.webp",
    "haut-puits-ilyana.webp",
    "haut-puits-vanniers.webp",
    "lecture des archives",
    "left sealed",
    "maintien des filtres",
    "nacelles-compagnes.webp",
    "nacelles-deux-rives.webp",
    "nacelles-frein.webp",
    "nacelles-trace.webp",
    "negotiation open",
    "non emporté",
    "non retenue",
    "not carried forward",
    "not selected",
    "now available for consultation",
    "négociation ouverte",
    "partage organisé",
    "prospère",
    "reinforced",
    "renforcé",
    "renfort des sas",
    "reserves protected",
    "restées scellées",
    "retenue, encore inachevée",
    "roads beyond Lower Watch",
    "routes au-delà de Veille-Basse",
    "réserves protégées",
    "scellée dans le châssis",
    "sealed into the chassis",
    "selected, still unfinished",
    "sharing organized",
    "sous charge",
    "thriving",
    "under load",
    "veille-basse-archives.webp",
    "veille-basse-cohorte.webp",
    "veille-basse-maelys.webp",
    "veille-basse-porte.webp",
    "À Veille-Basse",
    "À la tempête du Déversoir Noir",
    "Échanger des Matériaux de charpente contre le renfort des techniciens",
    "Échanger un relevé du Phare mobile contre des filtres étanches",
    "Échanges restants",
    "Éclaireurs de Haut-Puits",
    "Équipes de Maëlys maintenues à Veille-Basse",
    "Équipes envoyées sans Maëlys",
    "État dominant",
    "−30 L d’eau ; relation coopérative ; engagement au Conseil des Vannes.",
    "−30 L water; cooperative relationship; Sluice Council pledge."
  ],
  "nomsDAssets": [
    "deversoir-chassis.webp",
    "deversoir-conseil.webp",
    "deversoir-ligne-zero.webp",
    "deversoir-passage.webp",
    "haut-puits-decanteur.webp",
    "haut-puits-ilyana.webp",
    "haut-puits-vanniers.webp",
    "nacelles-compagnes.webp",
    "nacelles-deux-rives.webp",
    "nacelles-frein.webp",
    "nacelles-trace.webp",
    "veille-basse-archives.webp",
    "veille-basse-cohorte.webp",
    "veille-basse-maelys.webp",
    "veille-basse-porte.webp"
  ]
} as const;
